### ISSUE TITLE
Proposer un modèle de budget à publier pour encourager les équipes à le faire

### ISSUE THREAD

**Issue by adipasquale** [betagouv/beta.gouv.fr#10072]
Seuls deux services publient leur budget aujourd'hui : 

- [Mon entreprise](https://mon-entreprise.urssaf.fr/budget)
- [Collectif Objets](https://cyan-picture-b45.notion.site/Budgets-publics-des-services-1b5453be26234d1c9abcb6bbce577e58)

(cartobio a un lien mais il est cassé https://cartobio.org/budget)

Pour encourager les équipes à publier leur budget, on propose avec @lauriechap de proposer un modèle de page budget publique que les équipes pourraient dupliquer à leur guise. Ce modèle comprendrait :

- des lignes de budgets consommé par année et par poste (déploiement, développement, coaching) 
- des éléments de contextualisation pour expliquer :
- comment les marchés sont portés ; 
- que des indépendants interviennent ;
- les markups appliqués (il y aurait peut-être une "confidentialité" sur ces markups, à valider avec les juristes) ;
- des renvois vers des détails de budgets plus globaux, par ministère par exemple

Chaque SE pourrait évidemment décider de choisir parmi ces éléments, les compléter ou les amender.

La forme que prendrait ce modèle est à définir : template de page notion, template de page sur ce site beta, générateur de widget html à intégrer sur le site de la startup... 

Le but étant d'encourager les SE à publier, même a minima, il faudrait que ce soit aussi simple que possible, si possible pas de nouvel outil.

**Comment by mquandalle** [comment]
Bonne idée ! J'avais pensé aussi à une page dans la documentation qui pourrait être complémentaire et fournir une FAQ sur la publication du budget et le lien vers le template à remplir.

Si on ne veut pas de nouvel outil on peut se baser sur https://pad.incubateur.net ? Ou alors mieux vaut un outil type notion qui supporte l'affichage des sommes des lignes/colonnes d'un tableau ?

Pour les markups, je pense qu'il vaut mieux ne pas les afficher (confer discussion lors du séminaire sur la confidentialité de l'info), Florian me disait que de toute façon l'intérêt de la publication était plus dans les ordres de grandeur par produit que dans les montants exacts.

**Comment by astranchet** [comment]
Pour info, à date, 19 SE ont remplis ce champ.

**Comment by revolunet** [comment]
Hello, plusieurs actions ont été menées pour progresser là-dessus :

 - possibilité de soumettre [un formulaire GRIST](https://grist.incubateur.net/o/dinum/uTH6rofjCGP4/Declarations-budgets-startups/f/7) pour envoyer son budget à l'équipe beta
 - possibilité de publier son budget sur [le pad public](https://pad.numerique.gouv.fr/rHMnemklQm6Sww5yVCI9ow#) (migré vers pad.numerique)
 - une page [sur la documentation](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/gestion-administrative/publier-son-budget)
 - un [modèle sur le template-nextjs](https://betagouv.github.io/template-nextjs/budget) pour intégrer sur son site, inspiré de ce qu'on a trouvé sur certaines SE

On continue de contacter les startups qui n'ont pas encore fait les démarches

Je vous propose qu'on close cette issue
