### ISSUE TITLE
Renommage de l'organisation

### ISSUE THREAD

**Issue by guillett** [betagouv/beta.gouv.fr#1031]
- [ ] Archiver les dépôts qui devraient l'être
- [ ] Préparer la migration des GitHub Pages

**Comment by HelaG** [comment]
@jdesboeufs une idée de par où commencer ?

**Comment by Morendil** [comment]
Je vous proposerais bien de le faire en mode "exercice incendie": on créée une orga fictive et 2-3 dépôts, un Wiki, un petit site Github Pages. Ensuite on renomme à l'arrache, on voit ce qui casse, on fait un bilan de ce qu'on a appris (surtout ce à quoi on ne s'attendait pas).

Un atelier présentiel sur 2-3h ne me semblerait pas de trop pour l'exercice, compte tenu de la criticité/sensibilité de l'opération.

**Comment by Flightan** [comment]
Autre idée apporté par @guillett, créer la nouvelle organisation, puis transférer l'ownership projet par projet.
Points positifs:
 - diluer les risques
 - responsabiliser les équipes

Points négatif:
 - On passe de 1 manipulation de transfert à 108 manipulations

**Comment by jpic** [comment]
Je pensais que c'était plutôt facile, puisque [github s'occupe des redirections en cas de renommage](https://help.github.com/articles/renaming-an-organization/):

> GitHub automatically redirects references to your repositories. Web links to your organization's existing repositories will continue to work. This can take a few minutes to complete after you initiate the change.

**Comment by jdesboeufs** [comment]
@jpic GitHub ne gère pas les effets de bord type offloading nginx.

Le problème de partir sur une nouvelle organisation c'est qu'on repart de zéro pour tous les outils associés : CircleCI, Travis CI, Gitter etc.
On repart aussi de zéro pour les membres, les équipes, et on casse le lien HTTP vers notre organisation puisque cette URL ne sera pas redirigée. Bon d'un autre côté dès qu'un squatteur reprendra une organisation en `sgmap` on la perdra de nouveau.

**Comment by jdesboeufs** [comment]
Quoi qu'il en soit une telle orga existe déjà : https://github.com/BetaGouv

**Comment by jdesboeufs** [comment]
Organisation renommée.
