### ISSUE TITLE
Créer une fiche pour la startup déjà fermée à la DILA

### ISSUE THREAD

**Issue by guillett** [betagouv/beta.gouv.fr#1033]
Présenter l'irritant identifié et le post mortem (i.e. l'initiative de la gendarmerie avec expérimentation dans la région grenobloise).

**Comment by gregoirenovel** [comment]
@dlequepeys @TanguyYan up

**Comment by Morendil** [comment]
Un blog de @Yan est dans les tuyaux expliquant la décision de ne pas poursuivre, dans mon esprit ça serait une résolution de cette issue - partagez-vous cet avis ? Si non, quel valeur supplémentaire verriez-vous dans une fiche startup en plus du billet de blog ?

**Comment by gregoirenovel** [comment]
Done, cf. https://beta.gouv.fr/2018/02/28/comment-j-ai-mis-fin-a-ma-startup.html
