### ISSUE TITLE
Site beta gouv sur safari s'affiche mal (header) 

### ISSUE THREAD

**Issue by jihanehrz** [betagouv/beta.gouv.fr#1078]
Sur ma capture on voit encore le header mais avec une photo foncée on voit plus rien :) 
<img width="1269" alt="capture d ecran 2017-12-06 a 17 00 17" src="https://user-images.githubusercontent.com/32701234/33671128-160ae1c4-daa7-11e7-97b3-f3f57199e2ef.png">

**Comment by gregoirenovel** [comment]
@jihanehrz je ne reproduis pas le problème. Quelle version de Safari utilises-tu ? (Safari > À propos de Safari)

**Comment by Flightan** [comment]
J'avais posé la même question mais j'ai oublié de le renseigner dans cette issue. J'ai oublié mais c'est une ancienne version, a mon avis il ne supporte pas l'élément `<nav>` donc lui donne une `height` de 0. 

https://caniuse.com/#search=nav à priori une version antérieur à Safari 8.

**Comment by gregoirenovel** [comment]
Visiblement c'est même < 7 (version released le 22/10/2014).

Je propose une fermeture de l'issue ça touche très peu de monde.

**Comment by gregoirenovel** [comment]
En fait Jihane a le problème avec la 9.1.3

**Comment by Morendil** [comment]
@laem Tu peux reproduire avec ton compte BrowserStack ?

**Comment by laem** [comment]
Je confirme le :bug: sur Safari 9.1

**Comment by laem** [comment]
Corrigé sur 10.1

**Comment by laem** [comment]
J'ai pas pu débugger malheureusement, les DevTools sont pénibles...

Vu les [stats](https://caniuse.com/usage-table), vu que c'est pas un problème majeur, je pense qu'il faut pas passer plus de temps que ça dessus.

**Comment by gregoirenovel** [comment]
Je suis d'accord avec @laem, de plus le design va bientôt changer
