### ISSUE TITLE
🐛Fonction rechercher - page réalisations

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/beta.gouv.fr#10820]
Sur la page réalisation [ici@](https://beta.gouv.fr/startups/), lorsque je fais rechercher, il ne se passe rien. Je n'ai rien qui se passe dans la console non plus. ![image](https://user-images.githubusercontent.com/15428433/181017189-b017115f-c5b4-400f-b92f-03e3ed44a024.png)

**Comment by Flightan** [comment]
Merci @margot-sanchez , je prend.
