### ISSUE TITLE
Critère 8.2 - P01 - Accueil

### ISSUE THREAD

**Issue by julieSalha** [betagouv/beta.gouv.fr#11897]
La page contient des erreurs de code HTML qui peuvent impacter l'accessibilité.

Corrections à appliquer :

- Supprimer l'attribut id vide sur la balise `<body>`.
- Vérifier l'imbrication des balises de listes `<li>` et `</li>` dans la zone de sélection de langue du header : 
Supprimer la balise `</li>` isolée juste avant `<nav [...] title="Sélectionner une langue" >[...]</nav>`.

**Comment by astranchet** [comment]
@julieSalha je crois que tu as ouvert cette issue sur le github du site beta par erreur. (En tout cas, je ne reproduis pas sur le site de beta)
