### ISSUE TITLE
Nom de startup mal renseigné dans _jobs/2018-01-22-Lead-Dev-Startups-Ministere-Ecologie.md

### ISSUE THREAD

**Issue by fredZen** [betagouv/beta.gouv.fr#1232]
Dans [`2018-01-22-Lead-Dev-Startups-Ministere-Ecologie.md`](https://github.com/betagouv/beta.gouv.fr/blob/master/_jobs/2018-01-22-Lead-Dev-Startups-Ministere-Ecologie.md), la startup est renseignée comme suit

```
startup: Startups d'État du Ministère de l'écologie
```

Cette startup n’est pas renseignée dans [`_startup`](https://github.com/betagouv/beta.gouv.fr/tree/master/_startup)

L’effet est qu’elle ne s’affiche pas correctement. Dans le [listing d’offres d’emploi](https://beta.gouv.fr/recrutement/), le nom de la startup de l’annonce précédente est utilisé à la place :

![screenshot from 2018-02-07 15-17-00](https://user-images.githubusercontent.com/356570/35921106-0b6f2a28-0c1a-11e8-87bb-0c9e1f1021e2.png)

Et dans le [détail de l’annonce](https://beta.gouv.fr/recrutement/2018/01/22/Lead-Dev-Startups-Ministere-Ecologie.html), c’est un `beta.gouv.fr` générique qui apparaît :

![screenshot from 2018-02-07 15-18-18](https://user-images.githubusercontent.com/356570/35921156-293d12ea-0c1a-11e8-8231-b48828e3675e.png)

J’aurais bien proposé une correction, mais je ne trouve pas la startup dans [`_startup`](https://github.com/betagouv/beta.gouv.fr/tree/master/_startup). Peut-être faut-il passer cette annonce en `friend` comme [fun mooc](https://github.com/betagouv/beta.gouv.fr/blob/master/_jobs/2017-12-20-Developpeur-Python-Django-FUN.md) ?

**Comment by fredZen** [comment]
@MaximeBasset tu as peut-être des éléments d’information ?

**Comment by Morendil** [comment]
Je pense que c'est un bug de capture dans le layout de la page recrutement, ping @Flightan

**Comment by Morendil** [comment]
Il me semble que "friends" n'est pas approprié, on est bien dans la marque startups d'Etat. Je supprimerais le champ "startup", c'est bien beta.gouv.fr (la communauté) qui recrute.

**Comment by MaximeBasset** [comment]
@fredZen aucune idée non, désolé.
De mémoire c'était bien "beta.gouvfr recrute ..." sur la liste et sur la fiche recrutement il y a encore qq jours.

**Comment by fredZen** [comment]
Merci @MaximeBasset . Je t’avais pingé parce-que je me demandais si l’intention était d’avoir quelque chose comme « Startups d'État du Ministère de l'écologie recrute ». Entre ton intervention et celle de @Morendil je comprends maintenant que « beta.gouv.fr recrute » est OK.
