### ISSUE TITLE
Rendre explicite la mise à jour en continu du décompte sur le portefeuille

### ISSUE THREAD

**Issue by HelaG** [betagouv/beta.gouv.fr#1250]
Retour utilisateur qui nous demande où en est l'état du portefeuille parce que la mise à jour en continu du décompte sur beta.gouv.fr/startups/ n'est pas explicite. 

"J’étais allé sur votre site mais, sauf erreur, votre “compteur” n’est pas daté (problème fréquent sur internet). Je voulais donc m’assurer qu'il était bien à jour…"

<img width="960" alt="proposition 1" src="https://user-images.githubusercontent.com/12069445/36093585-61ffbd60-0feb-11e8-90f5-00f05da8c4f1.png">

**Comment by Flightan** [comment]
Je sais pas trop comment le faire, on ne garde pas de trace de la date des changements "investigation" -> "construction".
On peut afficher la date actuelle.

**Comment by HelaG** [comment]
Est-ce qu'on peut prendre la dernière date de modification sur le fichier /startups ?

**Comment by Flightan** [comment]
Ça semble théoriquement possible mais complexe 🐰

**Comment by Morendil** [comment]
On peut tenter d'avoir un champ quelque part (un fichier de config global par exemple) avec une date qu'on demanderait de mettre à jour lors de chaque création ou modification. C'est moins bien qu'un truc auto, mais ça répondra à la demande usager et on pourra l'améliorer par itération…

**Comment by gregoirenovel** [comment]
Je pense que ce n'est pas un problème, et qu'au contraire rajouter une date autre que la date du jour laisse penser qu'on n'a peut-être pas fait de MAJ depuis x jours (et donc qu'on est "en retard") alors que ce n'est pas le cas.

Est-ce qu'on a eu d'autres retours sur ce point ou on est dans le "1 fait divers, 1 loi" ?

**Comment by gregoirenovel** [comment]
> On peut tenter d'avoir un champ quelque part (un fichier de config global par exemple) avec une date qu'on demanderait de mettre à jour lors de chaque création ou modification.

On rajoute encore du process, on complexifie encore la contribution au site, ça va ralonger les temps de review, et c'est déjà certain qu'on va zapper de le faire 1 fois sur 2 IMO.

**Comment by Flightan** [comment]
Sinon on écrit en dessous "Tableau mis à jour en temps réel"

**Comment by gregoirenovel** [comment]
On est sur Internet en 2018, c'est temps réel par défaut partout, je ne vois pas pourquoi on le préciserait, *surtout si on n'a eu qu'un seul retour*.

**Comment by guillett** [comment]
FWIW : Wikipédia mentionne discrètement l'instant de dernière modification 
![capture d ecran 2018-02-13 a 11 57 01](https://user-images.githubusercontent.com/1410356/36146491-266a2e1e-10b5-11e8-93ae-53f5ad84438e.png)

Aussi, TPS a un lien sur sa page d'accueil vers [les releases GitHub](https://github.com/betagouv/tps/releases) 🙂.

**Comment by gregoirenovel** [comment]
Hmm la page releases de TPS, c'est pas forcément un indicateur de fraicheur de l'app (qui est d'ailleurs un concept différent de la fraicheur des données), mais plus la communication des modifications / ajouts faits au logiciel.

**Comment by Morendil** [comment]
Je ne vois que des 👎 et pas de piste viable pour répondre à la demande utilisateur : je ferme et vous propose si on nous interroge à ce sujet de répondre « on met à jour le site en continu ».
