### ISSUE TITLE
Améliorer les fiches des services numériques

### ISSUE THREAD

**Issue by astranchet** [betagouv/beta.gouv.fr#12767]
Depuis la PR  #9581, les fiches produits affichent un certain nombre de champs. Ils sont peu valorisés et difficilement distinguables les un des autres.
![image](https://user-images.githubusercontent.com/1374389/211014616-6445f7c4-8dd5-4adf-89ef-0e1a2ea2b84f.png)

Voici deux propositions pour mettre en avant ces informations :

## Proposition 1
Toutes les métadonnées sont au même niveaux. Elles sont regroupées en 3 groupes : 
- Les informations sur les **sponsors**, toujours de manière textuelles.
- Les indicateurs de **qualité**, avec une notion de note (couleur verte/orange/rouge)
- Les informations relative à la **transparence** sous forme de liens.
Les métadonnées sont présentées sous la forme d'une sidebar, ce qui a l'avantage de réduire un peu la place donnée au contenu du service (difficile à lire quand elle est très étalée en largeur)
![Proposition B](https://user-images.githubusercontent.com/1374389/211014655-45acaab7-36aa-47f7-b08a-ebd2dfec4618.png)

## Proposition 2
Les métadonnées sont hiérarchisées en deux groupes : 
- Les plus **importantes** (Contact, Mesures d'impact et les sponsors) sont en haut de la page.
- Plus bas, après l'équipe (ou avant ?) on retrouve le **détail des indicateurs de qualité et de transparence**. Un texte court explique les valeurs de l'incubateur.
![Proposition A](https://user-images.githubusercontent.com/1374389/211015434-47cc7e6f-a385-49c0-80ad-6730e55dcc1d.png)

À vos retours !

**Comment by Flightan** [comment]
J'aime beaucoup; je dirai que la proposition 1 me semble meilleure sur desktop et la 2 sur mobile.

S'il faut n'en faire qu'une et compter sur le dsfr pour le responsive, alors la 1.

**Comment by astranchet** [comment]
@Flightan sur mobile, la première proposition a pourrait donner un truc comme ça : 

![Mobile](https://user-images.githubusercontent.com/1374389/211024664-2f37b22a-d615-48b8-8302-a14dc7baa01d.png)

**Comment by Flightan** [comment]
Eh bien c'est très bien !

**Comment by freesteph** [comment]
j'aime beaucoup la 1 ! je trouve qu'en terme de hiérarchie de l'information et d'utilisation de l'espace c'est beuacoup beaucoup mieux que ce qu'on a actuellement et que la version 2 qui planque les indicateurs quali en bas et dont le bandeau central me paraît un peu luxueux. OK pour l'implémenter, j'espère que les screenshots (et leur ratio hyper variable) vont pas poser problème mais je posterai quelque chose ici.
