### ISSUE TITLE
Améliorer les pages Incubateurs

### ISSUE THREAD

**Issue by astranchet** [betagouv/beta.gouv.fr#12801]
Cette PR fait suite à un ping de @freesteph sur l'issue  #12711. 

Aujourd'hui, quand on veut des infos sur un incubateur, on a accès à deux pages : 
- La page **[Incubateurs](https://beta.gouv.fr/incubateurs/)** qui donne du détail sur chaque incubateur
- La page Réalisations filtrée sur un incubateur (ex [pour le MTES](https://beta.gouv.fr/startups/?incubateur=mtes))

La page Incubateurs notamment, a de sérieux problèmes de hiérarchie de l'information : 
- Pas d'intro, on rentre direct dans le vif du sujet
- D'ailleurs, sujet complexe : chaque incubateur est décrit, verbeusement et parfois avec des descriptions similaires
- Beaucoup d'actions sont proposées (voir le site, voir l'équipe, voir les réalisations...)
L'autre problème vient du parcours : on perd en continuité entre la page Incubateurs et la page Réalisations filtrées ; ça n'est pas très clair d'identifier quelle info on va trouver où.

Je propose de revoir un peu la composition de tout ça en partant sur deux page : 

### Une nouvelle page "Réseau beta.gouv"

Elle est voulu comme auto-portante, pour expliquer le principe de beta.gouv qui est à la fois un incubateur ET un réseau.
Ensuite, on présente hyper brièvement chaque incubateur. 

![Incubateurs](https://user-images.githubusercontent.com/1374389/211301135-b1c86d58-7819-4c8d-83d4-c51ebec83322.png)

### Une page par Incubateur 

C'est là qu'on a toutes les informations utiles à un incubateur. 

D'abord une description plus complète. (Notez que à cet endroit, contrairement à la page précédente, ce n'est pas gênant de "re-expliquer" ce qu'est un incubateur ; ce qu'aujourd'hui, chaque incubateur fait avec une tournure différente "concevoir et déployer des services numériques", "faire émerger et à soutenir de nouveaux services à impacts", "faire émerger des services numériques de qualité au service des usagers, répondant à des problèmes concrets", etc etc).

Ensuite, toutes les métadonnées type adresse, ministère... (et peut être date de lancement et nombre de services numériques actifs ?)

Enfin, les réalisations, directement sur a page. J'avais envie de les mettre toutes ensemble, avec un tag par statut (plutôt que séparées par statut comme actuellement).

![Incubateur](https://user-images.githubusercontent.com/1374389/211301107-a84d4ebd-ffb0-444f-be8c-75d7edab9690.png)

### Point à améliorer 

Bien sûr, ça n'est qu'une proposition ; et certains détails restent à être peaufinés. Par exemple : 

- Est-ce que les textes à propos de la nuance incubateur/réseau que je propose (issue de la doc) sont encore pertinents suites aux dernières restructurations ?
- Sur la page "Réseau beta.gouv", comment trier les incubateurs du réseau ? Je propose "par nombre de SE actives" (du plus gros incubateur au plus petit). C'est une solution pour donner moins d'importances aux incubateurs inactifs. 
- Où faire apparaître l'équipe des co-anims de beta ? Sur la page "Incubateur de la DINUM" (les co-anims sont des membres d'équipes d'animation, comme n'importe quel autre incubateur) ? Ou sur la page "Réseau" (car les co-anims ont aussi un rôle d'animation du réseau) ?

**Comment by freesteph** [comment]
@astranchet super, merci infiniment. Quelques questions qui me restent : 

* Sur la page index je vois des descriptions concises, cas qui n'est hélas pas la cas de nos infos actuelles (je prends ton exemple de l'ANCT : https://github.com/betagouv/beta.gouv.fr/tree/master/content/_incubators/anct.md). Ils sont tous d'ailleurs assez verbeux dans la description, donc est-ce que : 

  * je demande aux responsables de nous écrire un tweet (ça peut être un bon exercice pour eux de se limiter à 140/240 caractères) ;
  * je tronque la description à une longueur précise de cette taille^ ou similaire.

* On utilise pas vraiment les tuiles pour nos auteurs/membres actuellement, je me demande si par souci de cohérence on se doit de garder les cartes. Je note aussi que le DSFR les décrits (ces mystérieuses tuiles) comme des "raccourci ou point d’entrée qui redirige les utilisateurs vers des pages de contenu". Ici elles ne pointent pas forcément ailleurs.

* Sur notre partie (DINUM, au sommet de la page) il y a un "Voir l'équipe". C'est pas ça l'équipe des co-anims de Beta ?

* Après réflexion je trouve que trier par nombre de services incubés décroissants permet de filtrer très naturellement les incubateurs actif/inactifs donc mon vote vers ce système là.

**Comment by astranchet** [comment]
@freesteph 
- Sur la page index, je dirais _ni l'un ni l'autre_ : j'ai ré-écrit moi même les descriptions courtes, et je pense que c'est important que nous portions ces contenus.
    - La troncature n'est pas une stratégie de contenu (<insérer ici une image rigolote où le contenu tronqué affiche un truc genre "con..." au lieu de "content")
    - À mon sens, si on veut avoir un site qui tient la route, on ne peut pas laisser la main à la terre entière sur les contenus. En demandant à 18 personnes de "faire un tweet", c'est prendre le risque d'avoir 18 incohérences. Ou alors, il faut vraiment borner ce qu'on demande (par exemple "Compléter la phrase suivante avec moins de 150 caractères : "Mon incubateur vise à accompagner les services...")
   Après, je ne suis pas très fortiche en politique, mais je pense que l'ont peut se permettre "d'imposer" une description courte, justement parce que la description longue est un peu plus open bar. 

- J'ai vu qu'actuellement, on utilisait pas les tuiles ni les cartes effectivement. Dans mes maquettes, j'ai pris des composants du DSFR parce que je suis une feignasse. Et bien vu, normalement les tuiles sont des liens 🙈. J'aurais du mettre des cartes. Mais du coup, en taille "XS", car je pense qu'elles sont moins importantes que les cartes SE : 
![Capture d’écran 2023-01-09 à 15 19 26](https://user-images.githubusercontent.com/1374389/211329339-7b94123c-174c-43b1-a2ed-0ce746899986.png)

- Et yep, pour le moment, je suis partie sur le principe que "Voir l'équipe" permettait de voir les co-anims, sur la page dédié à l'incubateur DINUM. Mais je m'interrogeais si c'était le bon endroit. C'est une question un peu politique : est-ce que les co-anims bossent plutôt à l'incubateur ou pour le réseau ? (peut-être que ça dépend ; et là on est pas rendus 😅)

**Comment by IshanB** [comment]
Hello
C'est super d'avoir bossé sur ça !
Avec la réorganisation, il y a pas mal de choses qui vont changer, donc je
propose qu'on cale 2h vers la 2e semaine de février pour qu'on regarde
cette PR ensemble en synchrone, qu'en dites vous ?

**Comment by sneko** [comment]
Je viens de merger https://github.com/betagouv/beta.gouv.fr/pull/16399 . Pourriez-vous voir si ça correspond aux attentes initiales de l'issue ? (cf. https://beta.gouv.fr/incubateurs/)

Si "oui", je vous laisse la clôturer :)
