### ISSUE TITLE
obtenir mail no-reply@startup.beta.gouv.fr

### ISSUE THREAD

**Issue by Mhrtl** [betagouv/beta.gouv.fr#1293]
bonjour,

Locatio étant une startup G2C qui commence a avoir des utilisateurs, j'aimerais avoir une adresse de type no-reply@locatio.beta.gouv.fr (avec laquelle il soit facile d'envoyer des messages). Est-ce que c'est possible/est-ce qu'il y a une procédure définie ?

Merci beaucoup,
Matthieu

**Comment by jdauphant** [comment]
Je prends.
Je te créais une adresse. Pour des volumes supérieur à 50/100 mails par jour, il faudra passer sur un service comme Mailjet ou gérer l'envoi de mail avec un serveur.

**Comment by jdauphant** [comment]
Je viens de regarder et je ne peux que te faire des redirections mails pour une adresse en type locatio.beta.gouv.fr ( uniquement pour le domaine principal beta.gouv.fr).
Pour envoyer des mails, il faut utiliser un solution de type Mailjet ou gérer l'envoi de mail avec un serveur (il aura des paramètre DNS à nous communiquer dans ces cas là)

**Comment by Mhrtl** [comment]
ok ! Je vais voir ça avec Harlow alors

**Comment by Mhrtl** [comment]
merci beaucoup
