### ISSUE TITLE
Création d'un compte email générique pour l'envoi d'email automatisé sur le serveur de locat.io

### ISSUE THREAD

**Issue by Mhrtl** [betagouv/beta.gouv.fr#1295]
Obtenir mail no-reply-locatio@beta.gouv.fr

Bonjour, je souhaiterais obtenir l'adresse mail précédente afin de pouvoir paramétrer des envois de mails automatiques. Est-ce possible ? Nous sommes en train de monter les comptes clients et ce paramètre est très bloquant pour nous.

Merci beaucoup,
Matthieu pour Locatio

**Comment by maukoquiroga** [comment]
Bonjour @Mhrtl 

Nous avons l'habitude d'envoyer ce type d'emails avec le compte de l'équipe, par exemple ```contact@locatio.beta.gouv.fr```, et de répondre personnellement (n'importe quel membre de l'équipe) à tous les emails qui arrivent.

La création d'un compte ```no-reply``` irait à l'encontre du fait de mettre l'équipe qui crée un service numérique en contact direct avec ses usagers.

Quel est le facteur bloquant pour vous ?

**Comment by Mhrtl** [comment]
Je ne suis pas dev, aussi je ne sais pas quelles sont les difficultés cachées derrière ça, mais nous aimerions avoir une adresse "officielle" qui permettent d'envoyer des mails automatiques de confirmation. Or pour ce faire, et éviter les adresse nominatives ou les adresses en gmail, nous aimerions simplement avoir une BaL configurable permettant des envois de mails et terminant en beta.gouv (ou locatio.beta.gouv)
