### ISSUE TITLE
Pouvoir personnaliser les url /stats

### ISSUE THREAD

**Issue by HelaG** [betagouv/beta.gouv.fr#1311]
J'ai essayé d'actualiser le lien vers la page /stats sur la fiche Le.taxi
Le lien actuel renvoie une erreur 500
Les stats sont maintenant sur https://api.taxi/stats

La valeur stats est true or false, et ne peut pas être personnalisée :/

**Comment by Flightan** [comment]
C'était voulu, voir https://github.com/betagouv/beta.gouv.fr/issues/82

Si on force `<url du site>/stats`

Les +:
 - si elle n'existe pas, on peut considérer qu'elle n'existe pas (par exemple, un gdoc privé n'est pas une page `/stats`)
 - on a un vocabulaire commun, si des startups décident de changer de nom, ca passera par une issue ici et on peut en discuter, sinon c'est invisible pour la communauté
 - en interne / en externe si on comprend qu'il existe une convention, on sait qu'on peut aller voir le site de n'importe quelle startup et essayer `/stats`
 - pas besoin de réfléchir au nom de la page quand on met en place le truc

Les -:
 - c'est contraignant si on utilise des outils externes, les exemples sont [mes-aides](https://mes-aides.gouv.fr/stats), qui a du éditorialiser des graphes piwik, [la bonne boite](labonneboite.pole-emploi.fr/stats) qui force une redirection vers un outil externe et doc [le taxi](https://api.taxi/stats) pour des raisons techniques j'imagine.

**Comment by odtvince** [comment]
Je note que la plupart de ces + seraient également valables avec un `/stats` comme valeur par défaut qui puisse être écrasée par une valeur custom quand c'est nécessaire.

Sinon, pour rester en l'état, on peut probablement ajouter sur https://le.taxi/stats un lien ou une redirection vers https://api.taxi/stats

**Comment by HelaG** [comment]
@odtvince l'astuce de la redirection peut suffire dans notre cas.

Je trouve par ailleurs dommage de forcer un comportement dans le code sur beta.gouv.fr sur un sujet comme les métriques. L'attention d'une équipe à ces métriques d'impact est un travail qu'on tache d'"enforcer" par la pratique. Le fait que la valeur /stats soit figée n'apporte aucune valeur à l'équipe dans cet exercice.

**Comment by Morendil** [comment]
Je suis plutôt 👎 là dessus et 👍 pour des redirections. La simplicité est une vertu, les arguments de @Flightan me semblent convaincants.

"Ecraser par une valeur custom" ça veut dire que si on cherche les stats d'une startup on est obligés de passer par beta.gouv.fr, c'est une friction qu'on cherche à éviter en propageant comme norme "ajoute /stats au nom de domaine que tu viens de visiter". Il ne s'agit pas tant d'apporter de la valeur à l'équipe - elle peut tracker ses stats en privé - que de créer une norme et une émulation autour de cette norme. C'est le collectif qui bénéficie de la contrainte, et par ricochet le grand public.

Par comparaison si tu regardes dans le privé les startups d'infrastructure qui ont réussi, elles ont su imposer une norme de la "status page" status.domain.com, quand Github plante tu ne perds pas du temps à chercher où sont les infos, tu vas sur status.github.com, et savoir que ça marche comme ça crée de la confiance.

**Comment by Morendil** [comment]
@odtvince C'est censé être redirigé si je ne m'abuse https://github.com/openmaraude/le.taxi/blob/master/main.py ? Pourquoi est-ce que cette redir ne fonctionne pas ?

**Comment by Morendil** [comment]
Je ferme en laissant https://github.com/openmaraude/le.taxi/issues/101 qui est plus proche du besoin.
