### ISSUE TITLE
Bonjour, comment fait-on pour merger une pull request svp ?

### ISSUE THREAD

**Issue by VirginieLeB** [betagouv/beta.gouv.fr#13430]
Bonjour, comment fait-on pour merger une pull request svp ? 
Merci par avance pour votre aide ! Bonne journée !

_Originally posted by @VirginieLeB in https://github.com/betagouv/beta.gouv.fr/issues/13429#issuecomment-1447849152_

**Comment by jdauphant** [comment]
Géré par Amel sur une autre PR
