### ISSUE TITLE
Erreur 404 pour le manifeste beta gouv

### ISSUE THREAD

**Issue by mquandalle** [betagouv/beta.gouv.fr#13558]
La page https://beta.gouv.fr/approche/manifeste n'existe plus.
Elle est référencée sur https://beta.gouv.fr/approche (« lire notre manifeste ») ainsi que sur des sites externes comme https://datagir.ademe.fr/budget/

**Comment by NicolasBerthelot** [comment]
Bonjour, 
J'ai fix ce problème pour les pages beta.gouv.fr et déposé une issue pour la page référencée par datagir. Peut-être qu'une redirection de https://beta.gouv.fr/approche/manifeste vers https://beta.gouv.fr/manifeste réglerait plus largement le problème.

**Comment by jdauphant** [comment]
Merci pour l'issue et le correctif, désolé pour le temps de traitement, la PR c'est mélangé avec les très nombreuses PR de contenu
