### ISSUE TITLE
fiches produits markdown distant

### ISSUE THREAD

**Issue by ouhouhsami** [betagouv/beta.gouv.fr#1426]
Bonjour,

suite aux échanges du dernier séminaire, une idée : est-ce que vous seriez en mesure de rapatrier des fiches produits depuis d'autres comptes github ?

Nous copions collons les fiches produits sur notre repo https://github.com/MTES-MCT/numerique/tree/master/_startup depuis votre repo, mais nous pourrions héberger le markdown "source", et côté communauté beta gouv aspirer ces markdown lors de la statification de votre site ?

Le format est déjà là, il faudrait peut-être utiliser un plug'in jekyll qui utilise des URL distantes comme source markdown.

Qui en dit quoi ?

**Comment by jdauphant** [comment]
Mes remarques :
- ça peut bloquer la compilation du site beta s'il y a une erreur dans vos fiches
- il faudra faire une PR ou relancer la compilation côté beta pour mettre à jour le site en ligne
- en cas de mise à jour du format des fiches (ajout d'un champ par exemple), il faudra coordonnées les 2 repos (c'est pas pratique du tout surtout avec des contributeurs qui n'ont pas accès au 2 repos)
En fait, je ne vois pas d'avantage sur ce format avec jekyll :(

Je pousserais plus à ce que des gens de la fabrique numérique participent aux reviews.

**Comment by Morendil** [comment]
Il me semble que [la comparaison](https://xkcd.com/1205/) entre la fréquence de la tâche, le temps passé à la réaliser (y compris la correction des erreurs de synchronisation), et le temps qu'il faudrait pour l'automatiser n'est pas pour l'instant en faveur de l'automatisation. Je ferme pour l'instant, réouvrons en cas de bonne idée.

**Comment by ouhouhsami** [comment]
Je comprends ta réponse. Donc, je propose que nous hébergions sur notre github MTES-MCT les fiches produits source, et on trouve un moyen de les mettre à jour sur beta gouv ?

**Comment by jdauphant** [comment]
@ouhouhsami beta.gouv.fr est complètement statique pour le moment.
Ça voudrait dire que si vous modifiez vos fiches:
- il faudra faire une PR sur le repo beta.gouv.fr pour mettre à jour le site beta.gouv.fr (Le coût de cette solution est plus élevé pour vous)
- il faut réécrire beta.gouv.fr, changer le mode d'hébergement pour avoir une mise à jour des fiches (Le coût de cette solution est inconnu)

![Image](https://imgs.xkcd.com/comics/is_it_worth_the_time.png)

Le mieux ça serait d'améliorer la manière de travailler ensemble et de valider les fiches produits
