### ISSUE TITLE
Ajout de légendes pour les images

### ISSUE THREAD

**Issue by bzg** [betagouv/beta.gouv.fr#1428]
Je découvre https://beta.gouv.fr/startup/pop.html qui propose une photo sans citer ni [la source](https://commons.wikimedia.org/wiki/File:F54-Nancy-Maison-Schott-vitraux.jpg), ni l'auteur (François Bernardin), ni les droits (CC by-sa 3.0).

Il y a le même problème pour https://beta.gouv.fr/startup/plante-et-moi.html et peut-être d'autres.

Est-ce que `screenshot.html` peut évoluer pour présenter une légende ?

Je peux proposer un patch mais je ne suis pas sûr des aspects du layout à modifier.

Merci !

**Comment by Morendil** [comment]
@bzg Désolé du délai de réponse, tu as raison et on va corriger le tir. [Ce blog](https://beta.gouv.fr/2018/05/23/securite-numerique-produits.html) peut servir d'exemple pour le formatage.

**Comment by Morendil** [comment]
@bzg Celle de Plante&Moi est déjà attribuée.

**Comment by Morendil** [comment]
J'ai démarré une PR, on va passer en revue systématiquement les images autres que screenshots.

**Comment by bzg** [comment]
Super, merci beaucoup @Morendil !

**Comment by Morendil** [comment]
@bzg La plupart des autres photos utilisées dans la page startups (sinon toutes) le sont indirectement, via des screenshots de landing pages de produits qui utilisent des photos pas forcément attribuées. Celle de transport.data.gouv par exemple vient de [Unsplash](https://unsplash.com/photos/ZYfLkRgZJQk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText). Les images de Unsplash n'ont pas besoin d'être créditées mais c'est sans doute un moyen pratique de ne pas se poser de question sur le droit d'usage.

**Comment by bzg** [comment]
Oui, je vois deux arguments pour ajouter les crédits sur les images venant d'Unsplash: d'abord, ils disent que les photographes apprécient le geste, ensuite... ça évite, comme tu dis, de se demander quels sont les droits de réutilisation.

**Comment by bzg** [comment]
Le lien vers l'image dans POP n'est pas le bon: https://github.com/betagouv/beta.gouv.fr/pull/1520/commits/6d55717da5dfe2f657e87254dcbd3eae574d07c2#r195985311
