### ISSUE TITLE
Le registre des citoyens - Où est-ce?

### ISSUE THREAD

**Issue by cyberphone** [betagouv/beta.gouv.fr#1658]
Bonjour!

Je suis un résident français d'origine suédoise.

Apparemment, la France a décidé de "copier" le système utilisé en Estonie:
https://www.latribune.fr/technos-medias/la-france-et-l-estonie-renforcent-leur-cooperation-dans-le-numerique-772339.html
_"En Estonie, 99% des démarches administratives se font en ligne"_

Cependant, l’essentiel de l’architecture de gouvernement électronique estonien _n’est pas la carte d’identité électronique_, mais un **Registre Central de Citoyens** où chaque citoyen est reconnu par un **Numéro à 12 chiffres**:
https://www.siseministeerium.ee/en/population-register

En France, chaque département a son petit "registre des citoyens" et ses identités associées (CAF, IMPOTS, CARTE VITALE, etc etc.) ce qui est en réalité **l'INVERSE** du système estonien.

Je pense que cela rendra très difficile la réalisation de l'objectif ambitieux de 2022.  Pour ceux qui s'intéressent un peu à l'architecture des systèmes d'information, le "rapport de bogue" suivant peut être intéressant:
https://github.com/france-connect/identity-providers-examples/issues/9#issuecomment-403845522

Cordialement,
Anders Rundgren

**Comment by Morendil** [comment]
Bonjour Anders,

Merci pour ces remarques, et désolé d'apprendre que vous faites partie des personnes mal servies par FranceConnect.

Un identifiant unique équivalent unique existe en France, il s'agit du [NIR](https://fr.wikipedia.org/wiki/Num%C3%A9ro_de_s%C3%A9curit%C3%A9_sociale_en_France). Pour des raisons [historiques](https://donneesouvertes.info/2018/01/26/safari-la-chasse-aux-francais-40-ans-apres/) l'utilisation généralisée de cet identifiant comme clé de liaison entre bases de données administratives n'est pas (encore?) envisageable.

Vous avez raison de poser la question sur le dépôt de FranceConnect, c'est le bon endroit pour ces discussions ; je me permets donc de fermer l'issue ici - je ne vois aucune modification à apporter au site beta.gouv.fr qui résoudrait le problème que vous soulevez. ;)

**Comment by cyberphone** [comment]
@Morendil  Many thanx for the article: https://donneesouvertes.info/2018/01/26/safari-la-chasse-aux-francais-40-ans-apres/ it was great!  It even noticed that using using different identifiers doesn't stop "linking".  e-mail addresses, mobile phone number are **Globally Unique IDs**.  Add a little bit AI and you are all set 😀.

With respect to **beta.gouv.fr** it could actually be of some interest knowing how this relates to the announced pretty "bombastic" plans copying E-stonia.  

https://beta.gouv.fr/startup/api-particulier.html looks like a cool interim step which is just fine but it is not comparable to https://github.com/nordic-institute/X-Road#introduction-to-x-road which (of course) builds on having a unique Citizen ID and getting rid of tax number, etc. etc.

Anders
