### ISSUE TITLE
ETQ instructeur, je veux pouvoir appliquer des formules de calculs sur les champs

### ISSUE THREAD

**Issue by mfo** [betagouv/beta.gouv.fr#17056]
> ETQ instructeur j’ai besoin d’un champ qui est le résultat d’un calcul d’autres champs.

>    Contexte: à partir de plusieurs autres champs, dont le nombre de parts, le QF etc, des montants de subvention découlent d’un calcul. Ceci permettrait d’afficher d’ores et déjà l’égibilité, et de personnaliser la suite du formulaire en fonction.
    Idée d’implem: plutôt que recréer excel chez nous, s’appuyer sur un service tiers type walfram en charge du calcul :
        l’admin rentre la formule et les variables (les champs cibles)
        pour chaque dossier on envoie la requête au service et on récupère le résultat
    Autre piste: peut-être une gem permet d’avoir un système de calculette

**Comment by revolunet** [comment]
Bonjour a priori cette issue concerne demarches-simplifiées ? https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues
