### ISSUE TITLE
La balise <title> ne supporte pas la point médian.

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/beta.gouv.fr#1754]
Sur cette page : https://beta.gouv.fr/recrutement/2018/09/15/developpeu-r-se-2-camino.html la balise title a pour valeur : `Developpeu R Se 2 Camino — beta.gouv.fr`
La valeur attendue devrait être : `Camino recrute un·e développeur·se node.js et data`
D’instinct j'ai associé cette erreur au point médian, je me trompe peut être.

**Comment by Morendil** [comment]
Apparemment le `title` est dérivé du slug si tu ne donnes pas explicitement un titre à la page. C'est le slug qui donne cette étrange graphie, pas le point médian :

```
slug = developpeu-r-se-2-camino
title = Developpeu R Se 2 Camino
```

Il faudrait coder le `head` de façon à utiliser autre chose que le slug quand on peut, par exemple pour les recrutements, le titre du poste.

**Comment by Morendil** [comment]
Pour moi ça fait doublon avec l'autre issue, je ferme pour clarifier sur l'autre.
