### ISSUE TITLE
La balise  <meta property="og:title" est cassée

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/beta.gouv.fr#1755]
Sur cette page https://beta.gouv.fr/recrutement/2018/09/15/developpeu-r-se-2-camino.html la valeur de la propriété `content` de la balise `<meta property="og:title"` est `"Developpeu R Se 2 Camino"` cela devrait être `Développeur·se Camino`

**Comment by Morendil** [comment]
Apparemment le `title` est dérivé du slug si tu ne donnes pas explicitement un titre à la page. C'est le slug qui donne cette étrange graphie (et pas le point médian même si ça peut donner cette impression dans ce cas précis) :

```
slug = developpeu-r-se-2-camino
title = Developpeu R Se 2 Camino
```

Il faudrait coder le `head` de façon à utiliser autre chose que le slug quand on peut, par exemple pour les recrutements, le titre du poste.
