### ISSUE TITLE
Impossible de me connecter à l'espace membre

### ISSUE THREAD

**Issue by Ericdacosta12** [betagouv/beta.gouv.fr#17881]
Mon adresse email comporte 2 points, ce qui semble provoquer une erreur dans l'envoi de l'email pour me connecter à l'espace membre. Je n'arrive pas non plus à me connecter avec mon adresse secondaire
mon email : eric.da.costa@beta.gouv.fr
et la secondaire : ericdacosta.reva@gmail.com

**Comment by revolunet** [comment]
Merci pour le ticket, je ferme en faveur de https://github.com/betagouv/secretariat/issues/2355, un fix sera déployé rapiement
