### ISSUE TITLE
Problème d'alignement des auteur·e·s dans le blog

### ISSUE THREAD

**Issue by maukoquiroga** [betagouv/beta.gouv.fr#1796]
<img width="520" alt="capture d ecran 2018-09-24 a 20 37 36" src="https://user-images.githubusercontent.com/329236/45971589-ac3abe80-c039-11e8-8a52-af202cf948fa.png">

**Comment by monbocal** [comment]
C'est un problème au niveau des styles et des balises, le passage au template de thimy entraine ça.

Actuellement, les auteurs sont définis comme ça :

```
<address class="ui stackable cards">
  <div class="article__author panel">
    <div class="content">
      <div class="article__author-info">
        <div class="article__author-name">Sandra Chakroun</div>
        <div class="article__author-role">Développeuse</div>
      </div>
      <img alt="" src="https://avatars3.githubusercontent.com/sandcha?s=600">
      <div class="article__author-description">
      </div>
    </div>
  </div>
  <div class="article__author panel">
  ...
  </div>
</address>
```

Alors que le template nous demande de les décrire comme ça (source : template.data.gouv.fr ) :

```
<div class="article__author-list">
  <div class="article__author panel">
    <div class="article__author-info">
      <div class="article__author-name">Corgi</div>
      <div class="article__author-role">Intrapreneur</div>
    </div>
    <img src="images/template/corgi.jpg" alt="Corgi">
    <p class="article__author-description">The Welsh Corgi is a small type of herding dog that originated in Wales.</p>
  </div>
  <div class="article__author panel">
  ...
  </div>
</div>
```

J'ai demandé sur slack de l'aide pour avoir le site en local, c'est la seule chose qui me manque pour pouvoir tester et corrige ça.

**Comment by monbocal** [comment]
J'ai réussi à faire fonctionner, je prends du coup !

**Comment by maukoquiroga** [comment]
MErci !

**Comment by monbocal** [comment]
J'ai intégré le template, mais il y a un problème d'affichage sur l'empilement. Je suis en train de voir pour intégrer le système mis en place sur les pages startups (avec une grille) afin de régler ça.

**Comment by monbocal** [comment]
OK, alors j'ai intégré du mieux que j'ai pu, mais je pense qu'une mise à jour spécifique du style serait necessaire. Je prépare la PR.

**Comment by Morendil** [comment]
Fixed by #1805
