### ISSUE TITLE
Impossible de mettre à jour des fiches produits sur bêta

### ISSUE THREAD

**Issue by manon-silva** [betagouv/beta.gouv.fr#18026]
Bonjour, 
J'ai besoin de mettre à jour des fiches produits de SE de la Fabrique Num des Ministère Sociaux sur le site bêta mais au moment d'enregistrer la page avec les modifications effectuées, il ne se passe rien...
Quelqu'un sait à quoi c'est dû ? Et surtout comment faire en sorte que ça marche 😬
Merci d'avance !
<img width="1282" alt="Capture d’écran 2024-02-01 à 15 20 42" src="https://github.com/betagouv/beta.gouv.fr/assets/117319457/e3b673dd-6ba8-477f-b56b-5acfdfb7252b">

**Comment by revolunet** [comment]
Salut @manon-silva tu peux retester stp ?

**Comment by manon-silva** [comment]
C'est good maintenant ! Merci Julien 🙏🏻
