### ISSUE TITLE
Lien vers l'espace membre du mail de bienvenue non fonctionnel

### ISSUE THREAD

**Issue by JoeSlain** [betagouv/beta.gouv.fr#18101]
Lorsqu'on recoit le mail de confirmation de creation d'un email beta.gouv avec les etapes a suivre pour definir son mot de passe l'etape 1 `Étape 1 : Connecte toi sur l'espace membre` redirige vers https://espace-membre-api.incubateur.net/ mais le lien est down.

Peut etre que le bon lien devrait etre:
https://espace-membre.incubateur.net/login

EDIT: pareil pour le lien pour changer son mot de passe dans l'etape 2: https://espace-membre-api.incubateur.net/account#password

**Comment by revolunet** [comment]
Merci pour le retour on corrige ça

**Comment by revolunet** [comment]
De ce que [je vois](https://github.com/betagouv/espace-membre-next/blob/2d0466b887725247e15e9eeb33cabccfaf914614/src/server/views/templates/emails/createEmail.ejs#L5) ca été corrigé récemment, le front et l'API sont maintenant sur le meme host 😬

hésitez pas à réouvrir si c'est faux :)
