### ISSUE TITLE
Lisibilité des articles du blog

### ISSUE THREAD

**Issue by MaximeBasset** [betagouv/beta.gouv.fr#1823]
Très honnêtement, c'est perso ok, mais j'ai beaucoup plus de mal à rentrer dans le contenu avec ce nouveau format, la version précédente rendait les article du blog bien plus agréable à lire.

Possible d'augmenter la taille des polices et la largeur de la colonne centrale ?

**Comment by monbocal** [comment]
C'est quelque chose à voir avec @thimy , mais en attendant, on doit pouvoir forcer un style sur la nouvelle architecture. Je vais regarder ça.

**Comment by monbocal** [comment]
J'ai mis à jour le blog avec plus d'espace pour les articles et une légèrement plus grosse police de texte - https://blog.beta.gouv.fr/ , https://github.com/betagouv/blog.beta.gouv.fr/commit/e6d201fba6b150106bc7e26f6931ba9d9163f05a .

**Comment by yaf** [comment]
Ce ticket à plus d'un an, est-il toujours d'actualité ?

**Comment by Morendil** [comment]
@yaf Je pense que non :) je ferme donc
