### ISSUE TITLE
Suppression adresse mail de redirection

### ISSUE THREAD

**Issue by flofcq** [betagouv/beta.gouv.fr#1839]
Bonjour ! 

Je ne suis pas sur que cet endroit soit le bon pour poser cette question, mais je tente : j'ai deux adresses de redirection de mon mail en @beta.gouv.fr. Je souhaiterais ne garder que florent.passculture@gmail.com et supprimer florent.facq@gmail.com, comment faire ?

Merci !

**Comment by Morendil** [comment]
Ce n'est effectivement pas le bon endroit, passe par Slack ou http://secretariat-beta.herokuapp.com :)

**Comment by Morendil** [comment]
(N'hésite pas à me contacter directement sur Slack, je suis @hussardnum là-bas.)
