### ISSUE TITLE
Membres absent ou invisible

### ISSUE THREAD

**Issue by douglasduteil** [betagouv/beta.gouv.fr#18483]
Bonjour bonjour

Je me suis permis de rajouter [Maissarath](https://github.com/betagouv/beta.gouv.fr/pull/18083) et [Thomas](https://github.com/betagouv/beta.gouv.fr/pull/18343) dernièrement. Or @Anais-Tailhade m'a fait remarquer hier que sur la page [MonComptePro](https://beta.gouv.fr/startups/moncomptepro.html) : 
- Maissarath s'affiche ✅ 
- Thomas ne s'affiche pas ❌ 
- Douglas (moi) est recalé au fond de la salle derrière l'écriteau des anciens 😢 

![image](https://github.com/betagouv/beta.gouv.fr/assets/730511/f79f3a0e-0d63-4e86-9944-aaf2a7cda7e2)

**Comment by douglasduteil** [comment]
[friendly @revolunet ping]

**Comment by revolunet** [comment]
bien vu lulu

**Comment by revolunet** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTA1aWF5cGFycW5vcjR2Y2hoZTRqMGg1cjYyejJlaTZoeGF4M2J3eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/CNocEFcF9IBegtgW3q/giphy.gif)
