### ISSUE TITLE
Graph d'évolution des effectifs

### ISSUE THREAD

**Issue by ClementChapalain** [betagouv/beta.gouv.fr#1872]
~J'ai peur d'avoir cassé qqchose en mettant à jour 2 profils (#1870 #1871) sur la page communauté~ 
Le graph fonctionnait ce matin et maintenant il ne s'affiche plus :
https://beta.gouv.fr/communaute/
![image](https://user-images.githubusercontent.com/5337489/46868956-80d21500-ce2a-11e8-84b0-76f74bff9bf7.png)

**Comment by Morendil** [comment]
Si tu veux éviter ça à l'avenir:
- fais tes PR sur le dépôt et pas sur un fork (tu as les droits en écriture sur le dépôt)
- utilise les review apps pour vérifier ton travail

Avec de grands pouvoirs viennent de grandes responsabilités :)

**Comment by Morendil** [comment]
Cela dit il est possible que ça ne vienne pas de tes PR… je ne vois pas d'erreur évidente.

**Comment by Morendil** [comment]
Bon ça ne vient pas de toi, un CDN qu'on utilise est down et la référence à https://oss.maxcdn.com/jquery/2.2.2/jquery.min.js part en 404. Don't worry.

**Comment by ClementChapalain** [comment]
ok merci pour toutes les infos !

**Comment by ClementChapalain** [comment]
c'est revenu grâce à #1873 :)
