### ISSUE TITLE
La création d'une organisation enfreint 2 règles de validation

### ISSUE THREAD

**Issue by sneko** [betagouv/beta.gouv.fr#19631]
* Nouvel enum manquant dans `schema/startups.yml`
* La fiche de l'organisation a un champ "id" qui n'est pas autorisé

cf. https://github.com/betagouv/beta.gouv.fr/pull/19600

**Comment by revolunet** [comment]
j'ai désactivé ce check dans `./schema` au profit des schemas zod dans `./ci`
