### ISSUE TITLE
Ajouter du lazy loading pour les images de la page communauté

### ISSUE THREAD

**Issue by totakoko** [betagouv/beta.gouv.fr#2006]
Chez moi, la page [communauté](https://beta.gouv.fr/communaute/) met 10 secondes à se charger et afficher le graphique lors d'une visite initiale.

L'un des problèmes de cette page est que les images doivent toutes être récupérées avant l'affichage du graphique (10Mo à télécharger et DOMContentLoaded à 8.5s...).

On pourrait ajouter du lazy loading pour récupérer les images censées être affichées à l'écran et ainsi accélérer grandement le chargement initial.

J'ai potentiellement le correctif prêt ajouter du lazy loading sur les avatars des gens. Puis-je faire une PR ?

**Comment by HelaG** [comment]
Fais une PR @totakoko 🙏
