### ISSUE TITLE
Mise à jour compte avec nouvelle mission et nouvelles dates

### ISSUE THREAD

**Issue by AnGi44** [betagouv/beta.gouv.fr#20117]
Suite à une date de fin de mission expirée sur le projet "Ecobalyse", je n'arrive pas à restaurer mon compte pour lancer une nouvelle mission : "seves". Est-ce possible de restaurer le compte angi.bidault@beta.gouv.fr ? #incubateur-help 
```[tasklist]
### Tasks
```

**Comment by revolunet** [comment]
Bonjour @AnGi44 est-ce que tout est rentré dans l'ordre ?

**Comment by AnGi44** [comment]
J'ai l'impression que c'est good merci !

**Comment by revolunet** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbThjOGY3eWV0Y2FkN3Bobm5vdGZrMGZzbWdiNWN0cmhlNWtyMGk4cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qGrCvOrjLELDFrc3Bm/giphy.gif)
