### ISSUE TITLE
Visbilité des images de startups

### ISSUE THREAD

**Issue by guillett** [betagouv/beta.gouv.fr#2060]
Les images des startups sont rognées car elles n'ont pas toutes, le même format. C'est dommage car le rendu sur les pages est moyen.

![capture d ecran de 2018-12-11 17-04-20](https://user-images.githubusercontent.com/1410356/49812981-de210e80-fd66-11e8-9940-f59e9c9edef5.png)

**Comment by Morendil** [comment]
Plus d'actualité depuis les évolutions apportées par @monbocal, je ferme
