### ISSUE TITLE
Typo Startup d’état Prélèvements d’Eau

### ISSUE THREAD

**Issue by marc-bouvier** [betagouv/beta.gouv.fr#20648]
Bonjour,

J'ai l'impression qu'il y a une typo sur la fiche de la startup Prélèvements d’Eau.

J'ai essayé de faire une PR mais je lis qu'il faut passer par [l'espace-membre](https://espace-membre.incubateur.net).

Comme je ne fais pas partie de Béta Gouv, je relaie sur cette Issue.

Typo supposée : `en charte de` -> `en charge de`

```diff
- Par ailleurs, les **données ne sont pas centralisées et facilement accessibles**, ce qui rend difficile leur consultation et leur partage entre les différents acteurs impliqués (préleveurs, services et établissements publics de l'Etat en charte de l'instruction des demandes d'autorisation et de leur contrôle, agences et offices de l'eau...).  
+  Par ailleurs, les **données ne sont pas centralisées et facilement accessibles**, ce qui rend difficile leur consultation et leur partage entre les différents acteurs impliqués (préleveurs, services et établissements publics de l'Etat en charge de l'instruction des demandes d'autorisation et de leur contrôle, agences et offices de l'eau...).  
```

https://github.com/betagouv/beta.gouv.fr/blob/b7a32ba4c32fe1c2a1ac5b66bbbf1107985ec588/content/_startups/prelevements.deau.md?plain=1#L34

**Comment by revolunet** [comment]
oops désolé pour le délai; c'est corrigé et sera en ligne prochainement
