### ISSUE TITLE
Chargement images produit

### ISSUE THREAD

**Issue by revolunet** [betagouv/beta.gouv.fr#20811]
Il y a un souci avec l'image de [c'est qui le pro](https://beta.gouv.fr/startups/investigation-ij.html) qui n'apparait pas sur le site alors que présente sur espace-membre et dans le bucket.

RAS dans les logs scalingo 🤔 

<img width="352" alt="Capture d’écran 2024-10-11 à 10 38 59" src="https://github.com/user-attachments/assets/2731d2bf-9f55-4e7f-b746-9f4228e9292f">

---

Une solution possible pour le problème de chargement des images serait de télécharger une fois les images qui nous intéressent au début du build, exemple avec `s5cmd cp 's3://bucket/startups/*' ./img/startups`

**Comment by freesteph** [comment]
> Une solution possible pour le problème de chargement des images serait de télécharger une fois les images qui nous intéressent au début du build, exemple avec `s5cmd cp 's3://bucket/startups/*' ./img/startups`

Solution similaire dans #20837
