### ISSUE TITLE
Lisibilité des textes surlignés

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/beta.gouv.fr#2089]
Lors d'une présentation beaucoup basée sur le site, il est assez pratique de surligner des passages de texte que l'on veut mettre en valeur pour en parler.

**Le problème** : les couleurs sont différentes en fonction des navigateurs / systèmes et ce n'est pas toujours lisible.
Dans notre cas : OSX + Chrome c'est surligné en bleu foncé avec texte en noir => illisible.

**Proposition**: configurer des couleurs qui marchent pour unifier l'XP.

Les contre-exemples sous Ubuntu :
Chrome
![chrome](https://user-images.githubusercontent.com/1656255/50224703-d123a100-039e-11e9-83b7-4cdf3738572f.png)

Firefox
![firefox](https://user-images.githubusercontent.com/1656255/50224705-d123a100-039e-11e9-95e1-8ad326764457.png)

**Comment by rap2hpoutre** [comment]
@jonathanfallon Ce serait possible avec le pseudo-élément `::selection`. À noter : sur MDN, il y a une mise en garde d'accessibilité à propos de l'habillage du texte sélectionné, https://developer.mozilla.org/fr/docs/Web/CSS/::selection#Accessibilit%C3%A9. Tu proposerais quoi pour unifier ?

**Comment by jonathanfallon** [comment]
Le code couleur de Chrome est le plus lisible.
Pour ce qui est de l'accessibilité, ça permettrait de l'améliorer dans notre cas ;)

**Comment by Morendil** [comment]
@jonathanfallon Je vais fermer ce ticket car sans avancée depuis plus d'un an, ce qui me fait supposer que tu as trouvé d'autres moyens de traiter le problème; n'hésite pas à intervenir ici si c'est toujours d'actualité.

A supposer que ça soit encore le cas, j'avoue être un peu mal à l'aise avec l'idée de chercher à contrer le comportement laissé libre aux navigateurs, aux fins de traiter un use case dont je ne sais pas à quel point il est répandu. J'ai l'impression qu'une solution intermédiaire consisterait à utiliser les extensions qui existent et sous Chrome et sous Firefox, du type "web highlighter", qui proposent de donner un degré de contrôle sur le surlignage de textes sur le web.
