### ISSUE TITLE
ordre des missions et affichage des équipes

### ISSUE THREAD

**Issue by revolunet** [betagouv/beta.gouv.fr#20908]
Il semblerait que l'ordre défini dans le markdown des fiches membres joue sur l'affichage ou pas dans membre dans une équipe.

Il faudrait se baser sur les dates de missions et non leur ordre

ex: https://github.com/betagouv/beta.gouv.fr/pull/20903

**Comment by freesteph** [comment]
> Il semblerait que l'ordre défini dans le markdown des fiches membres joue sur l'affichage ou pas dans membre dans une équipe.

c'est juste l'ordre qui n'est pas celui attendu non ?

> 
> Il faudrait se baser sur les dates de missions et non leur ordre
> 
> ex: #20903

**Comment by revolunet** [comment]
@guillett quel est le souci d'affichage exactement ?

<img width="221" alt="Capture d’écran 2024-11-27 à 20 02 01" src="https://github.com/user-attachments/assets/a5e9f5a7-dbf1-462e-a783-ac05b3cdccc7">
