### ISSUE TITLE
Commande /trad dans Slack

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/beta.gouv.fr#2192]
Hello,

Dans [le wiki](https://github.com/betagouv/beta.gouv.fr/wiki/Slack#trad), il est mentionné l'existence d'une commande `/trad`, pour obtenir la signification d'acronymes.

- La commande est inactive actuellement. Est-elle abandonnée ? Faut-il la réparer ?
- Où se trouve le glossaire ?

**Comment by Morendil** [comment]
Poke @MattiSG - tu veux bien nous aider à reprendre la main là-dessus ?

**Comment by AntoineAugusti** [comment]
@MattiSG Pourrais-tu dire où se trouve le répertoire avec la liste des acronymes ?

**Comment by monbocal** [comment]
Je suis en train d'investiguer

**Comment by monbocal** [comment]
Got it ; je vais récupérer le code et ouvrir sur github la liste des commandes de traduction

**Comment by monbocal** [comment]
OK, alors ça se passe à travers une base de données sql, c'est pas le plus pratique du monde, je regarde si y'a pas un autre bot du même type qui pourrait faire le job

**Comment by monbocal** [comment]
J'ai réactivé la commande /trad, mais ça cafouille un peu, on est au max des intégrations.

Le code du bot est au https://github.com/codeforamerica/glossary-bot .

Solution proposée : repartir de 0 ?

**Comment by AntoineAugusti** [comment]
Est-ce qu'il existe un dump des différentes abréviations et de leur signification ?

**Comment by Morendil** [comment]
On va considérer ça comme un abandon, personne n'ayant eu l'énergie pour le réparer… j'ai supprimé les entrées sur `/trad` et `/compte` de la page correspondante de notre wiki.
