### ISSUE TITLE
S'adresser aux profils tech sur la page d'accueil

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/beta.gouv.fr#2225]
Bonjour,

Actuellement sur la page d'accueil, on propose du contenu axé vers les :
- Agents publics
- Décideurs publics

Mais pas des profils techniques souhaitant s'impliquer dans la réalisation des services numériques de l'État. Le seul endroit dédié à ces profils est la partie "Recrutement".

Est-ce que la situation actuelle convient ? Faut-il s'adresser à ces profils dès l'accueil ?

**Comment by adipasquale** [comment]
En effet, quand j'ai découvert le site Beta Gouv j'ai trouvé ça très flou, abstrait, je n'ai pas bien compris comment c'est organisé. Ça ne met pas en valeur les méthodes, technos, et l'organisation qui sont appliquées, alors qu'il y a beaucoup de choses séduisantes. 
J'ai eu le même retour d'une amie développeur qui cherche un poste et est intéressée par Beta Gouv mais a trouvé ça très flou.

**Comment by ClementChapalain** [comment]
+1 pour les profils tech, et on peut aussi ajouter les profils design / coach / pm dans la réflexion je pense

**Comment by laem** [comment]
Je greffe ici un sujet qui me semble proche : une mention "code libre par défaut" à côte des 3 points du manifeste, qui ferait un lien vers github.com/betagouv, répondrait à mon avis à une bonne partie des questions que se pose un dev.

**Comment by monbocal** [comment]
Je pense qu'on peut aller plus loin et proposer une nouvelle taskforce "Page d'accueil". Eventuellement avec le soutien de la com' / autres ?

**Comment by bsabardu** [comment]
Hello, je suis d'accord, en tant que PM on cherche comment aider mais difficile de savoir comment c'est organisé et comment on peut s'impliquer

**Comment by Morendil** [comment]
Je vais fermer faute de plans concrets pour traiter ce point spécifiquement; une réflexion sur le design du site est en cours.
