### ISSUE TITLE
Nouvel onglet "Pré-incubation"

### ISSUE THREAD

**Issue by monbocal** [betagouv/beta.gouv.fr#2313]
Travail avec Ines @ineshijazi et Jihane @jihanehrz pour ajouter un onglet "Pré-incubation" (nom de code) sur le site beta.gouv.fr .

Deadline : 5 juin 2019.

L'onglet contiendra des "protofiches startups" (nom de code). Deadline pour mise en forme : 20 mai.

Autres pages de prévues actuellement :
- une partie "Historique" avec les présentations des promos précédentes
- une partie "Présentation"
- une partie "Inscrivez-vous à la prochaine session !"

Il faudrait également pouvoir lier des Startups d'État avec leur fiche produit de préincubation éventuelle.

Cette issue est ouverte pour ne pas oublier le sujet et pour partager les avancées.

**Comment by Morendil** [comment]
Fait depuis longtemps…
