### ISSUE TITLE
Mettre à jour le template avec la version 1.2

### ISSUE THREAD

**Issue by monbocal** [betagouv/beta.gouv.fr#2329]
https://github.com/etalab/template-jekyll

Je m'y colle ASAP.

**Comment by monbocal** [comment]
Bien entendu, je rencontre des problèmes, et comme on est vendredi soir, c'est risqué de mettre en ligne maintenant.

**Comment by monbocal** [comment]
Branche : maj-template-jekyll

**Comment by Morendil** [comment]
Cette branche n'existe plus et je ne sais pas dans quelle mesure ce ticket est encore d'actualité; je ferme.
