### ISSUE TITLE
Pouvoir spécifier quand une startup a pivoté

### ISSUE THREAD

**Issue by johangirod** [betagouv/beta.gouv.fr#2429]
La startup "Simulateur de coût d'embauche" vient de pivoter pour devenir "mon-entreprise.fr". 
Nous avons donc mis à jour la fiche produit correspondante (#2305)

Le problème, c'est que l'on perd l'historique de la startup, notamment la fiche produit ainsi que le nom des personnes ayant travaillé sur la startup avant son pivot.

Une piste de solution : 
- Ajouter un nouvel état de startup : "pivoté", avec un lien vers la nouvelle fiche
- Sur la nouvelle fiche, ajouter un lien vers l'ancienne fiche

Si personne ne voit d'inconvénient à cette solution, je ferai une PR.

**Comment by monbocal** [comment]
Je vais réfléchir à ce sujet une fois que j'ai terminé mon chantier actuel sur les fiches des auteurs. Merci de l'avoir soulevé !

**Comment by Flightan** [comment]
@johangirod vas-y pour la PR 👍

**Comment by Flightan** [comment]
En s'inspirant de https://incubateur.social.gouv.fr/startups/work-in-france/ ("Les évènements marquants"), on pourrait imagine que ce pivot soit un type d'évènement parmis d'autres ? Création, changement de phase, fin avec raison etc ?

**Comment by Morendil** [comment]
C'est pas forcément dramatique de perdre l'historique, et on a récemment un petit avertissement via les réseaux sociaux que le côté jargonnant du terme "pivoter" n'est pas du goût de tout le monde. Perso je ne ferais rien de plus que ce que vous avez déjà fait.

**Comment by Morendil** [comment]
Je ferme le ticket, faute d'avancées, n'hésitez pas à rouvrir pour une proposition court terme.
