### ISSUE TITLE
Citer la politique de contribution de l'Etat aux logiciels libres dans la page Licences

### ISSUE THREAD

**Issue by bzg** [betagouv/beta.gouv.fr#2475]
La page [Licences](https://github.com/betagouv/beta.gouv.fr/wiki/Licences) pourrait utilement citer ou renvoyer à la [politique de contribution de l'Etat aux logiciels libres](https://www.numerique.gouv.fr/publications/politique-logiciel-libre/).

**Comment by Flightan** [comment]
C'est fait merci !

**Comment by bzg** [comment]
Merci !
