### ISSUE TITLE
Ajouter l'adresse opensource@data.gouv.fr pour la page Licences

### ISSUE THREAD

**Issue by bzg** [betagouv/beta.gouv.fr#2476]
Sur la page [Licences](https://github.com/betagouv/beta.gouv.fr/wiki/Licences), n'hésitez pas à m'indiquer comme référent logiciels libres si les gens ont besoin d'explications ou d'accompagnement sur le choix des licences.  Soit en donnant mon email, soit celui-ci: opensource@data.gouv.fr

**Comment by Flightan** [comment]
C'est fait merci !

**Comment by bzg** [comment]
Merci beaucoup !
