### ISSUE TITLE
Expliciter les cas d'utilisation de licences à réciprocité

### ISSUE THREAD

**Issue by bzg** [betagouv/beta.gouv.fr#2477]
L'explication de l'usage de l'AGPL sur la page [Licences](https://github.com/betagouv/beta.gouv.fr/wiki/Licences) est un peu lapidaire. Pourquoi l'AGPL comme seule licence restrictive ?

Peut-être expliquer le raisonnement: 
  - Par défaut, on doit choisir une licence permissive;
  - Si l'intérêt général est en cause, alors on peut choisir une licence à réciprocité;
  - Parmi les licences à réciprocité homologuées, l'AGPL est souvent utilisée pour les startups car elle couvre aussi le cas des modifications apportées côté serveur.

**Comment by Flightan** [comment]
C'était notre meilleure proposition à l'époque, le débat portait déjà sur ton premier point: "Par défaut, on doit choisir une licence permissive". Notre première version était encore plus tranchée puisqu'elle ne mentionnait que AGPL.
Peux-tu expliquer pourquoi ça te semble si évident ?

Je propose:
 - Par défaut, choisir une licence permissive, la licence [MIT](https://spdx.org/licenses/MIT.html#licenseText) est un choix fréquent;
 - S'il y a un risque de réappropriation nuisible au service, on peut choisir une licence à réciprocité, la licence [AGPL-3.0](http://www.gnu.org/licenses/agpl-3.0.fr.html) est une licence souvent utilisée car elle couvre aussi le cas des modifications apportées côté serveur.

**Comment by bzg** [comment]
Je pense que c'est utile d'en profiter pour citer la liste des licences homologuées et qu'il faut éviter l'expression "réappropriation nuisible au service", qui laisse croire qu'il s'agit d'un problème éventuel de concurrence.

Je propose:

- Par défaut, choisir une licence permissive parmi celles [homologuées](https://www.data.gouv.fr/fr/licences).
- Si la publication sous licence permissive va à l'encontre de l'intérêt général, alors utiliser une licence à réciprocité, faible ou forte, parmi les licences à réciprocité [homologuées](https://www.data.gouv.fr/fr/licences) ; il faut alors explicitement motiver ce choix.

La formulation est faite pour encourager l'utilisation de licences permissives et pour inciter à demander des précisions si les auteurs craignent pour l'intérêt général.

**Comment by Morendil** [comment]
Je vais fermer considérant que les modifs de Florian du 21/4 traitent le sujet. @bzg je t'invite à réouvrir si ça te semble insuffisant

**Comment by bzg** [comment]
Je me permets de réouvrir : les deux éléments importants à faire figurer dans la page [Licences](https://github.com/betagouv/beta.gouv.fr/wiki/Licences) sont: (1) la notion d'_intérêt général_, aujourd'hui absente et (2) la notion de _charge de la preuve_ pour l'administration souhaitant utiliser une licence restrictive: cette administration doit apporter des éléments probants indiquant qu'une restriction _proportionnée_ est indispensable dans l'intérêt général.

Il y a aujourd'hui [36 dépôts publiés sous AGPL à beta.gouv.fr](https://code.etalab.gouv.fr/fr/repos?g=https%3A%2F%2Fgithub.com%2Fbetagouv&license=AGPL), il faudrait que beta.gouv.fr puisse vraiment justifier l'usage de l'AGPL pour chacun d'eux.

Mon ressenti: l'AGPL est souvent utilisé dans l'idée qu'elle seule permet de créer un bien commun, elle est privilégié quand on se dit « on veut éviter les passagers clandestins et on souhaite forcer les éventuelles entités repreneuses à contribuer en retour sans fermer la ressource ».

Je comprends cette envie mais... (1) la licence ne fait pas le commun: on a de beaux communs avec des licences permissives et des non-communs avec de l'Affero et (2) ça me paraît être une lecture trop libre de la loi pour pour une République numérique.

À  suivre, donc :)

**Comment by bzg** [comment]
PS: Je n'ai pas les droits pour rouvrir l'issue, je te laisse ce soin @Morendil - merci !

**Comment by tristanrobert** [comment]
Je vais aller dans le sens de @bzg . Le sujet du choix de la licence n'est pas anodin et pourrait avoir des conséquences sur la croissance d'une startup. Dans la doc: https://doc.incubateur.net/startups/developpement/qualite-du-code#appliquer-une-licence, il est écrit: 

> S'il y a un risque de réappropriation nuisible au service, la licence AGPL-3.0 est une licence souvent utilisée. Dans le cas contraire, la licence MIT est un choix fréquent. 

Cette phrase et la suite de cette page suggère que par défaut c'est la licence AGPLv3 qui est à privilégier pour se protéger d'une mauvaise appropriation et qu'on pourrait éventuellement prendre MIT dans le cas contraire. Ne pourrait-on pas inverser? La croissance d'un produit peut gagner grâce à l'écosystème qu'il engendre (Etat plateforme) et notamment économique avec les contributions des entreprises pas toujours réciproques mais pas toujours nuisibles non plus. C'est l'utilité même de ces licences libres et permissives. En tout cas, il faudrait préciser dans quel cas l'obligation de réciprocité serait utile à une startup d'Etat.  Ne pourrait-on pas plutôt proposer par défaut une licence permissive (MIT, etc) pour favoriser cet écosystème économique (Etat plateforme avec des APIs offertes aux entreprises et citoyens) et une licence à obligation de réciprocité si on souhaite freiner cela et cela se justifierait (acteurs économiques nuisibles?).

**Comment by jdauphant** [comment]
Je rejoins @tristanrobert MIT par défaut et une licence non-permissive si justifié (par les dépendances ou pour éviter une réutilisation nuisible)

**Comment by Flightan** [comment]
@bzg à proposé :
 

> https://doc.incubateur.net/startups/developpement/licences
> 
> Il suffit de modifier cette partie :
> 
>  « S'il y a un risque de réappropriation nuisible au service, la
>  licence AGPL-3.0 est une licence souvent utilisée. Dans le cas
>  contraire, la licence MIT est un choix fréquent. »
> 
> Je propose à la place :
> 
>  « Lorsque des restrictions à la réutilisations sont justifiées,
>  l'usage de licences homologuées plus restrictives est envisageable
>  (voir ce guide interactif* pour le détail).  C'est ce que explique
>  l'utilisation de la licence AGPL-3.0 dans nombre de nos dépôts. »
> 
>  https://guide-juridique-logiciel-libre.etalab.gouv.fr
> 
> L'idée de la modification est
> 
> 1. de dire qu'il faut que les licences restrictives soit justifiées ;
> 2. de renvoyer à une source plus détaillée (le guide) si besoin ;
> 3. de bien mentionner l'AGPL comme licence couramment utilisée.

J'ai mis à jour la page pour prendre en compte ce retour, est-ce que vous pensez qu'on peut clore cette issue ?

**Comment by bzg** [comment]
Pour moi oui, merci d'avoir pris le temps !
