### ISSUE TITLE
Code couleur non expliqué 

### ISSUE THREAD

**Issue by lucasverra** [betagouv/beta.gouv.fr#2769]
![image](https://user-images.githubusercontent.com/11323803/61580787-d94ee500-ab15-11e9-8469-0ee07862d989.png)

**Comment by BuyukCem** [comment]
Je souhaiterai contribuer à ce projet.
Il faut ajouter une legende en haut de page selon les codes couleurs ?

**Comment by Morendil** [comment]
Merci pour la proposition @BuyukCem ! N'hésite pas à forker et ouvrir une PR en lien avec cette issue. Je serais plutôt favorable à un séparateur entre les deux catégories comme sur la page [communauté](https://beta.gouv.fr/communaute), ces couleurs dénotent "les membres actifs" et "les anciens" respectivement.

**Comment by Flightan** [comment]
Le code couleur n'est plus utilisé ajd.
