### ISSUE TITLE
Problème de responsivité sur écrans larges

### ISSUE THREAD

**Issue by IshanB** [betagouv/beta.gouv.fr#2774]
La bannière n'est pas centrée à partir d'un certain niveau de résolution

![Screenshot 2019-07-26 at 10 08 37](https://user-images.githubusercontent.com/28890473/61936678-83eb5b80-af8d-11e9-8dfe-c38b2016250d.png)

**Comment by Morendil** [comment]
N'est plus d'actualité il me semble…
