### ISSUE TITLE
Créer https://beta.gouv.fr/wiki qui redirige vers le wiki

### ISSUE THREAD

**Issue by Anna-Livia** [betagouv/beta.gouv.fr#2786]
Mon soucis : 
Je trouve qu'il est difficile de trouver le wiki quand on n'est pas très au courant des outils de la communauté betagouv (ex : nouveaux arrivants)

Il me semble qu'il est plus facile de communiquer sur le wiki aux nouveaux arrivants en leur donnant l'URL "https://beta.gouv.fr/wiki " que de leur expliquer comment se rendre sur
`https://github.com/betagouv/beta.gouv.fr/wiki/`

Solution 
- Je propose de créer une redirection de https://beta.gouv.fr/wiki vers https://github.com/betagouv/beta.gouv.fr/wiki/
- Je propose de remplacer le `à propos` du header en `wiki`

**Comment by jdauphant** [comment]
On peut faire wiki.beta.gouv.fr aussi, je ne sais pas lequel à le plus de valeur.

Pour "à propos", la page existante est intéressante pour les gens en dehors de beta (sinon il faudrait refaire l'accueil du wiki)

**Comment by Anna-Livia** [comment]
J'aime beaucoup l'idée de `wiki.beta.gouv.fr`qui est beaucoup plus communicable que l'adresse actuelle ^^

**Comment by jdauphant** [comment]
J'ai fait la redirection mais je ne peux pas la configurer en ssl pour le moment

**Comment by Anna-Livia** [comment]
C'est top merci !

**Comment by jdauphant** [comment]
@Anna-Livia On peut faire un gitbook automatiquement à partir du wiki : (on peut le générer tout les jours ou X heures)
J'ai fait un essai : https://betagouv-1.gitbook.io/wiki/ (Il faut personnaliser)
Avec le repo de test ici : https://github.com/betagouv/beta.gouv.fr.wiki-autoclone

**Comment by jdauphant** [comment]
Ça permet de soulager par rapport à l'interface Github pour les nouveaux (et non habitué à Github), la recherche est plus accessible. 
Et pour les utilisateurs actuels, le workflow est le même (edition ou consultation sur le wiki du repo sur Github), il n'y a pas de changement.

**Comment by Anna-Livia** [comment]
Je suis d'accord avec toi.

**Comment by jdauphant** [comment]
Bon, il y a des limitations, les liens et les smileys ne fonctionnent pas (il doit y avoir une incompatibilité de Markdown). Je ne vais pas creuser plus pour le moment mais dispo pour en discuter

**Comment by Morendil** [comment]
Corrigé.
