### ISSUE TITLE
Onglet Préincubation :

### ISSUE THREAD

**Issue by JenniferStephan** [betagouv/beta.gouv.fr#2892]
- Maj de la description du programme de préincubation (/doc programme)
- Sur le menu :
-- Ajouter les collectivités et la date de lancement des promotions
--  Ajouter les nouvelles promotions (1 par collectivité ?)
- Je propose de faire rédiger les fiches des nouvelles équipes dans le cadre de la formation Alpha de lancement

**Comment by Morendil** [comment]
Done il me semble
