### ISSUE TITLE
Créer une section "Amis"

### ISSUE THREAD

**Issue by IshanB** [betagouv/beta.gouv.fr#3155]
Créér une section "Amis" pour les communautés amies : 
- OpenFisca
- OpenAcadémie

**Comment by Intendant-zonard** [comment]
Hello,
l'adresse https://openacademie.beta.gouv.fr/ ne répond plus : qu'arrive-t-il !?

**Comment by Morendil** [comment]
@Intendant-zonard Je regarde…

**Comment by Morendil** [comment]
Changement de l'adresse IP sous-jacente du côté de Netlify je pense, j'ai mis à jour avec la bonne IP pour le CNAME et ça devrait corriger le souci… jusqu'au prochain changement.

Le souci c'est qu'on ne peut pas avoir en même temps un hébergement sur Netlify avec un domaine personnalisé (openacademie.beta.gouv.fr) et des adresses mail associées à contact@openacademie.beta.gouv.fr. Enfin on peut mais périodiquement on va avoir ces soucis lorsque l'hébergeur migre le site sur une nouvelle adresse IP.

Je vais réfléchir à ce qu'on peut faire pour une solution pérenne.

**Comment by Intendant-zonard** [comment]
Merci !

**Comment by Morendil** [comment]
J'aimerais bien qu'on étende cette partie envisagée à des produits ou des équipes "inspirés de la démarche beta" mais pour lesquels nous ne prenons pas les mêmes engagements.

Par exemple certains des produits dont les fiches sont actuellement en discussion et pour lesquels la stratégie d'investissement est "on va financer 6 mois puis passer en MCO" et l'impact visé est au bénéfice d'un petit nombre d'agents publics plutôt qu'un grand nombre d'usagers.

J'ai conscience que ces deux cas (OpenAcadémie d'une part, le covoiturage des scellés que j'ai en tête comme exemple d'autre part) n'ont pas tout à fait les mêmes caractéristiques, mais on peut peut-être les regrouper pour éviter de multiplier les catégories…

**Comment by IshanB** [comment]
Oui, je suis aligné, tu proposes d'intégrer ça à la PR de Florian ?
Ou de faire une nouvelle PR ensuite ?


Le lun. 27 avr. 2020 à 16:47, Laurent Bossavit <notifications@github.com> a
écrit :

**Comment by Morendil** [comment]
Une autre PR à suivre

**Comment by revolunet** [comment]
Toujours d'actu ?

**Comment by Intendant-zonard** [comment]
Bonjour,

Non, OpenAcadémie a été éjectée de l'orbite beta.gouv, vous pouvez fermer les propositions de ce genre. On essaie de survivre par nos propres moyens dans le milieu hostile du MEN, et pour l'instant ça dure encore.

Bonne année à l'incubateur et à la DINUM, cordialement,


----- Mail original -----
> De: "Julien Bouquillon" ***@***.***>
> À: "betagouv/beta.gouv.fr" ***@***.***>
> Cc: "Intendant-zonard" ***@***.***>, "Mention" ***@***.***>
> Envoyé: Lundi 8 Janvier 2024 10:13:00
> Objet: Re: [betagouv/beta.gouv.fr] Créer une section "Amis" (#3155)
> 
> 
> 
> 
> 
> Toujours d'actu ?
> 
> —
> Reply to this email directly, view it on GitHub , or unsubscribe .
> You are receiving this because you were mentioned. Message ID:
> <betagouv/beta . gouv . fr/issues/3155/1880620624 @ github . com>

-- 
Étienne ANDRÉ
http://www.intendancezone.net
Tél direct 01 49 40 21 22

**Comment by revolunet** [comment]
Merci pour les précisions et bonne chance à vous pour 2024 !

Cordialement
