### ISSUE TITLE
Renommer l’incubateur "dinsic" en "dinum" ?

### ISSUE THREAD

**Issue by ronnix** [betagouv/beta.gouv.fr#3474]

**Comment by chaibax** [comment]
Cela semble avoir été fait. Peux tu confirmer @ronnix et fermer l'issue?

**Comment by ronnix** [comment]
Ma question concerne les champs `owner` et `incubator` dans les fiches startups, qui utilisent toujours respectivement `DINSIC` et `dinsic` comme identifiants.

Cf. par exemple https://raw.githubusercontent.com/betagouv/beta.gouv.fr/master/content/_startups/zam.md

**Comment by Morendil** [comment]
Fixed by #3631
