### ISSUE TITLE
"Les anciennes et les anciens" dans une fiche startup n'inclut pas les personnes avec un champ "previously"

### ISSUE THREAD

**Issue by jdauphant** [betagouv/beta.gouv.fr#3864]
"Les anciennes et les anciens" affiche uniquement les membres sorties de la communauté.

Les membres encore dans la communauté avec un champ "previously" ne sont pas affiché.

Code source ici :
https://github.com/betagouv/beta.gouv.fr/blob/274e1c8e9d76419267547b9595ebe00cc1d58138/_includes/grid-authors.html

**Comment by PieterjanMontens** [comment]
J'ai aussi remarqué le problème, j'ai quelques exemples étranges:
## PIX
Pix affiche bien le bouton "anciens": https://beta.gouv.fr/startups/pix.html
Or au moins un des anciens en question n'est pas dans la catégorie "anciens" (équipe sous `previously`) :  https://raw.githubusercontent.com/betagouv/beta.gouv.fr/master/content/_authors/quentin.cattez.md

## ANDI
Pour ANDi je suis effectivement "ancien" : https://raw.githubusercontent.com/betagouv/beta.gouv.fr/master/content/_authors/pieterjan.montens.md 

Or je n'apparais pas dans la fiche : https://beta.gouv.fr/startups/andi.html


Je veux bien participer à la solutionner le problème, mais je ne vois pas encore d’où il vient, et quel rôle joue https://github.com/betagouv/beta.gouv.fr/blob/master/search.json (qui semble pourtant correct)

**Comment by jdauphant** [comment]
Le code source fautif est ici : https://github.com/betagouv/beta.gouv.fr/blob/274e1c8e9d76419267547b9595ebe00cc1d58138/_includes/grid-authors.html#L23

En ne prends en compte que la date de fin de contrat et le champs "startup". 
Il faut introduire l'usage de previously dans `{%- assign team = site.authors | where:"startups", startup_id -%}`  et comparer le previously en plus au niveau de `{%- if timestampNow > timestampEnd -%}`

**Comment by PieterjanMontens** [comment]
J'ai pris l'option de faire une seconde boucle sur les anciens membres: les différencier s'ils font tous partie de la même liste devenait bien trop complexe.

**Comment by PieterjanMontens** [comment]
Ça m'a l'air résolu, cf la PR.
Exemple pour ANDi:
https://deploy-preview-3928--beta-gouv-fr.netlify.app/startups/andi.html

Exemple pour PIX:
https://deploy-preview-3928--beta-gouv-fr.netlify.app/startups/pix.html

(exemples à comparer avec mon commentaire plus haut)

**Comment by PieterjanMontens** [comment]
Corrigé:
https://beta.gouv.fr/startups/andi.html
https://beta.gouv.fr/startups/pix.html

**Comment by jdauphant** [comment]
Merci @PieterjanMontens :wink:
