### ISSUE TITLE
Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur

### ISSUE THREAD

**Issue by Flightan** [betagouv/beta.gouv.fr#4311]
(Relevée par un audit rapide du site par l'équipe DesignGouv et Access42)

Dans le menu de navigation, la page active est mise en évidence par la couleur:

<img width="590" alt="Capture d’écran 2020-09-24 à 11 10 20" src="https://user-images.githubusercontent.com/1475946/94125380-8e85d700-fe56-11ea-8cf9-50ac5b0d1b31.png">

Dans ce cas, ajouter un titre de lien (attribut title) sur le lien en suivant ce modèle : "Notre approche, page active." 

> Lorsqu’une information est donnée par la couleur, il faut qu’elle soit également donnée par une autre méthode, par exemple par un texte qui donne la même information.
> En effet, l’absence d’alternative à l’information donnée par la couleur représente une perte d’information pour certains utilisateurs.
> Ainsi, ces éléments purement visuels ne seront pas perçus par les personnes aveugles et les grands malvoyants qui utilisent un lecteur d’écran.
> Ceux-ci poseront aussi des problèmes aux personnes déficientes visuelles en particulier aux personnes qui perçoivent mal ou pas les couleurs (comme les daltoniens).
> Dans certains cas il est nécessaire de donner une alternative visuelle à la couleur, afin de répondre aux besoins des personnes déficientes visuelles n’utilisant pas de technologie d’assistance pour consulter la page (les daltoniens par exemple). Pour ces utilisateurs, il faut utiliser un indice visuel leur permettant de distinguer l’élément actif des éléments inactifs, sans s’appuyer uniquement sur la couleur. Il peut s’agir d’un symbole, d’une texture, de chiffres.

**Comment by astranchet** [comment]
Ancien design
