### ISSUE TITLE
Les pages Formations contiennent des vidéos qui proposent une transcription textuelle au format PDF : ces fichiers ne sont pas accessibles. Il s’agit d’un impact majeur d’accessibilité.

### ISSUE THREAD

**Issue by Flightan** [betagouv/beta.gouv.fr#4312]
(Relevée par un audit rapide du site par l'équipe DesignGouv et Access42)

Assurez-vous que chaque document soit accessible (cf. les Guides de créations de documents bureautiques accessibles7), ou remplacez les PDF par des transcriptions structurées (docx, HTML) qui reprennent toutes les informations présentes (visuelles et sonores) dans la vidéo.

https://github.com/DISIC/guides-documents_bureautiques_accessibles

<img width="688" alt="Capture d’écran 2020-09-24 à 11 12 47" src="https://user-images.githubusercontent.com/1475946/94125627-e290bb80-fe56-11ea-8634-679c507845a8.png">

**Comment by Morendil** [comment]
D'après nos stats la partie MOOC du site représente moins de 1% du trafic; elle est "enterrée" dans une profondeur de navigation qui la rend quasi invisible (j'ai presque envie de dire inaccessible). Si on prévoit d'investir du temps ou des efforts sur son accessibilité, il me semble que cet effort pourrait inclure aussi une meilleure mise en avant du contenu.

**Comment by astranchet** [comment]
La page Formations n'existe même plus
