### ISSUE TITLE
Impossible d'ajouter "Fabrique numérique des ministères sociaux" sur une fiche produit dans Netlify

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#4595]
Sur Netlify, quand on créée une fiche produit, il n'est pas possible de trouver "Fabrique numérique des ministères sociaux" dans la liste déroulante.
Il y a "Fabrique numérique" mais celle du MTES.

**Comment by LeryJ** [comment]
La fiche incubateur de la fabrique numérique des ministères sociaux existe bien pourtant.

**Comment by LeryJ** [comment]
@revolunet pour info

**Comment by revolunet** [comment]
j'avais raté ca :) mais apparemment c'est réglé depuis
