### ISSUE TITLE
Impossible de retirer un membre d'une SE si sa fiche n'a pas de date de fin via netlify

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#4601]
Via Netlify, une intra a voulu retirer son ancien coach de sa SE.
La fiche de ce coach n'a pas de date de fin. 
Il y a un message d'erreur qui ne permet pas de valider la fiche car le champs "date de fin" est obligatoire.

**Comment by Morendil** [comment]
Je ne suis pas certain qu'on souhaite "corriger" ce "bug", je veux dire par là que rendre la date de fin obligatoire est une décision délibérée - on a jugé que le bénéfice de renseigner systématiquement ce champ était au final supérieur à l'inconvénient que ça génère.

Est-ce que "renseigner d'abord une date de fin, puis modifier la fiche" te semble une solution acceptable, et si non pourquoi ?

**Comment by jdauphant** [comment]
La date de fin est maintenant obligatoire
