### ISSUE TITLE
Modification de la  fiche produit ma cantine

### ISSUE THREAD

**Issue by valeriemerle** [betagouv/beta.gouv.fr#4732]
Une alimentation saine, de qualité, durable et accessible à tous en restauration collective
Garantir un système permettant une alimentation saine, durable, moins animale et plus végétale, respectueuse de la production et du climat, peu émettrice de gaz à effet de serre et accessible à tous, notamment en rendant la loi EGAlim connue de tous.
15 millions de Français prennent chaque jour au moins un repas hors de leur domicile, dont plus de la moitié en restauration collective. Cette spécificité française fait de la restauration collective un passage obligé pour de nombreux français. Au total, ce sont près de 100 000 structures de restauration collective, publiques ou privées, qui distribuent plus de 3,5 milliards de repas par an. Compte tenu de l’importance de ce secteur, il est essentiel d’en faire un levier de premier plan dans la transformation de notre modèle alimentaire. La restauration collective est un levier puissant pour faire évoluer les pratiques alimentaires, réduire les inégalités et recréer de la valeur ajoutée pour les filières locales. Ce projet s’inscrit dans le cadre du Programme National de l’Alimentation, piloté par le Ministère en charge de l’Agriculture et de l’Alimentation.
Accompagner les acteurs de la restauration collective vers des initiatives responsables en accord avec EGAlim
La loi dite « EGAlim » du 30 octobre 2018 a introduit de nouvelles obligations pour la restauration collective. Elle fixe notamment un objectif d’au moins 50 % de produits durables et de qualité, dont au moins 20 % de produits biologiques, dans la composition des repas servis à partir du 1er janvier 2022. Or, il existe peu de données sur la qualité de l’alimentation dans ce secteur en France. Ainsi, il est difficile d’apprécier la mise en œuvre de ces objectifs et les niveaux actuels d’approvisionnement en produits de qualité et durables dans les restaurants collectifs.
Par ailleurs, les attentes des citoyens envers leur alimentation sont extrêmement fortes : une alimentation respectueuse de la santé et de l’environnement. La loi EGAlim impose aux restaurants collectifs d’informer les convives de la qualité alimentaire et nutritionnelle et de part des produits de qualité et durables entrant dans la composition des repas servis.
Bilan de l’investigation
De début septembre à fin octobre 2020, une équipe de beta.gouv.fr et une intrapreneuse de la direction générale de l’alimentation (DGAL) ont mené une investigation pour mieux comprendre l’écosystème, les attentes et besoins de toutes les parties prenantes de la restauration collective. L’équipe interroge institutions, acheteurs publics, cuisiniers, prestataires, fournisseurs, commensaux, opérateurs privés et publics… afin de proposer une hypothèse de solution qui réponde véritablement à leurs besoins. Le comité final de présentation des résultats auprès de la DGAL du 29 octobre a été concluant et a validé la construction du produit imaginé suite à cette phase d’investigation.
Ma Cantine, auto-diagnostiquer ma cantine scolaire et mettre en place les actions pour une transition vers une alimentation plus saine et durable
Le secteur de la restauration collective étant vaste et très divers dans son organisation, ses pratiques et son fonctionnement, l’hypothèse de solution proposée est une plateforme numérique dont la cible est volontairement restreinte, dans un premier temps, aux cantines scolaires autogérées.
Cet outil, Ma Cantine, permettra à une élu·e, chef·fe de cantine, gestionnaire… d’évaluer sa conformité avec l’ensemble des mesures de la loi via un test de positionnement et notamment de calculer la part de ses achats de qualité et durables grâce à la mise à disposition d’une calculette simple et facile à prendre en main. Cet autodiagnostic l’aidera à évaluer les pistes d’amélioration pour garantir des assiettes plus saines et durables à ses convives, via un tableau de bord et l’accès à des ressources adaptées à sa situation.
La forme de l’outil, qui se veut encourageante, facile d’accès et interactive, sera déterminée au fil de sa construction au pas à pas avec des cantines pilotes. De premiers établissements ont déjà formulé leur désir de faire partie des beta-testeurs.
Ma Cantine est la première brique d’une plateforme numérique, pouvant être, après expérimentation, élargie aux autres secteurs de la restauration collective, si les résultats et l’impact attendus sont montrés sur ce premier secteur d’expérimentation. Cet outil évaluant la “compatibilité de ma cantine à la loi” permettra également de tester le recueil des données permettant de faire l’état des lieux de la part des produits durables et de qualité au sein de la restauration collective en France.

**Comment by jdauphant** [comment]
@IshanB tu veux aider @valeriemerle  sur sa fiche produit ?
