### ISSUE TITLE
Afficher l'incubateur d'accueil sur une offre d'emploi

### ISSUE THREAD

**Issue by Flightan** [betagouv/beta.gouv.fr#4771]
L'incubateur relié à une offre d'emploi n'est pas affiché aujourd'hui sur les annonces de la page /recrutement.
Un contournement de plus en plus utilisé est d'ajouter l'attribut "friend" pour le préciser. 

Ce n'est pas le plus qualitatif car il devient alors difficile de relier l'offre à une page produit, ou bien à une page de description de l'incubateur quand le poste est transverse.

**Comment by renardpal** [comment]
résolu depuis n'est-ce pas ?

**Comment by Flightan** [comment]
En effet ! Merci @renardpal
