### ISSUE TITLE
Trouver une manière de faciliter le merge avec la fonctionnalité "up to date" active

### ISSUE THREAD

**Issue by jdauphant** [betagouv/beta.gouv.fr#4907]
La fonctionnalité "up to date" + l'attente des tests créé beaucoup d'attente pour pouvoir merger une PR.

Idée de solutions :
- [ ] Avoir des tests super rapide
- [ ] Avoir un bot qui merge les pull requests validé à la suite

**Comment by revolunet** [comment]
je pense qu'on peut close @jdauphant ?

**Comment by jdauphant** [comment]
Oui en effet, c'est une fonctionnalité native de github
