### ISSUE TITLE
Ajout d'un bot d'automerge

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/beta.gouv.fr#5085]
Le processus de merge est long, il faut updater la branche, attendre que les tests tournent, et merger la P.R. Et ceci pour plusieurs PRs.
Idéalement  certaines PR pourraient être mergées automatiquement, après review ou non. On pourrait considérer si tout est validé en amont que certaines PRs n'ont pas besoin de review (quand elles viennent de l'interface secretariat/par netlify par exemple). Dans tous les cas les choses seraient simplifiées si l'ajout d'un simple label pouvait automatiser l'update, l'attente de tests valides et le merge.

### Tentative avec le `github action` pascalgn/automerge-action
Ce bot merge autmatiquement la branch master dans la PR et merge ensuite la PR dans master quand on rajoute un label `automerge` à la PR et que les `test checks` sont bons.
- Dans le cas où la PR est déjà up to date, l'action marche
- Dans le cas où elle ne l'est pas, la gitub action fait l'up to date, puis attends que les tests checks passent. Les tests checks ne se relancent pas aprés l'up to date fait par la github action, et donc tout devient bloqué. Seul une action d'un utilisateur sur la PR, relance le processus et l'ensemble du workflow marche.

Une des tentatives a été d'utiliser l'event `workflow_run` sur le workflow de test avec les valeurs suivantes :
```
name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["automerge"]
    branches: [master]
    types: 
      - completed
```
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run

Le worflow_run permet normalement de déclencher les tests une fois "automerge" completed. L'utilisation de 2 workflow automerge,  l'un qui `complete` tout de suite aprés un update branche, et donc permet aux tests de se relancer, et un autre qui continue de tourner (et pourra donc merge une fois les tests passés) devrait normalement fonctionner en théorie.

Ancienne PRs:
https://github.com/betagouv/beta.gouv.fr/pull/4507
https://github.com/betagouv/beta.gouv.fr/pull/5083

**Comment by LucasCharrier** [comment]
Un système mettant en place workflow_run devrait pouvoir marcher, le tests avec les deux actions automerge étant un peu un hack, il y a peut être un conflit ou autre qui explique que ce n'ai pas marché.

Une autre solution semble d'utiliser un token lié a un vrai utilisateur (ce que fait Pix): 
https://github.com/1024pix/pix/pull/1623/files

Ainsi l'update est réalisé par un utilisateur ce qui a pour effet de relancer les tests.

**Comment by Morendil** [comment]
Je continue à être sceptique sur la direction que vous prenez, et je n'ai pas l'impression que mes remarques sur #4507 (au début de la discussion, donc de début novembre) ont été prises en compte.

Qu'est-ce que vous cherchez à faire exactement, si on parle seulement de la finalité et pas des détails d'implémentation ? Quel problème cherche-t-on à résoudre ? Si on le mettait sous la forme d'un [Current Reality Tree](https://online.visual-paradigm.com/knowledge/problem-solving/what-is-current-reality-tree/) ça donnerait quoi ?

Même en admettant que la bonne solution soit un auto-merge je ne comprends pas cette issue. D'après ce que j'ai compris on a déjà activé la fonctionnalité "auto-merge" qui est désormais une feature de Github, pourquoi est-ce qu'il y a besoin de continuer sur un bot en plus de cette fonctionnalité ?

**Comment by LucasCharrier** [comment]
@Morendil 
J'ai bien lu l'historique de la discussion, et je suis d'accord en effet avec tes observations. 

La feature de Github "auto-merge" permet en effet de lancer un merge si tout passes mais requiert quand même que la branche soit updatée. Donc tu auras beau cliquer sur `automerge` (la feature github), à partir du moment ou quelques choses à changer sur master, toutes les PRs que tu avais mises en `automerge` ne seront plus mergées et faudra à nouveau passé sur chacune et faire `update`.

Le bot d'automerge, te permet, de mettre le label `automerge` sur les PRs validés à merger, sans avoir à retourner dessus pour faire les `updates` à la main. 

Ça diminue juste le nombre d'action à faire, et le temps d'attente entre elles pour le reviewer.

**Comment by Morendil** [comment]
J'ai [appris](http://www.humansystemsinaction.com/lullaby-language/) à me méfier du mot "juste" ;) la question c'est de savoir si le résultat obtenu (diminuer le nombre d'actions) est suffisamment intéressant pour compenser le coût (le temps qu'on passe à discuter de cette feature et à l'implémenter, le temps qu'on passera dans le futur à la maintenir si elle pose des problèmes nouveaux, le temps de s'habituer à ses conséquences inattendues…)

J'ai l'impression notamment qu'on se focalise sur l'automatisation au détriment de considérer les autres "branches" du problème par exemple "pourquoi est-ce que les tests sont si longs" ou même "pourquoi est-ce qu'il y a beaucoup de PR qui se retrouvent longtemps en attente"… sans avoir la certitude que réaliser un auto-merge sera une solution complète au problème constaté. (Et sommes-nous même bien d'accord sur le problème…)
