### ISSUE TITLE
La double barre de défilement rend la navigation bizarre

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#5572]
Sur un PC 13 pouces, la double barre de défilement rend la navigation complexe.

![image](https://user-images.githubusercontent.com/43180136/113828498-bf8b8080-9784-11eb-85d2-0eb0a25ba48b.png)

**Comment by Flightan** [comment]
Je pense qu'il y a trop d'éléments sur cette page, tous les textes de phases devraient selon moi être sur la doc, ils sont trop long pour un format site web de présentation global.

**Comment by LeryJ** [comment]
Apparemment c'est réparé !!! Bravo

**Comment by Flightan** [comment]
Oui j'ai modifié tout le menu :) merci !
