### ISSUE TITLE
Le clic pour la recherche d'une SE est compliquée

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#5595]
Lorsqu'on recherche un produit à partir du moteur de recherche, il y a une série de proposition.
Il n'est pas évident de distinguer où cliquer.
Il n'y a pas de distinctions entre le nom du produit (cliquable) et le reste non cliquable (sponsor + description).
![image](https://user-images.githubusercontent.com/43180136/114037227-11b1cc00-9881-11eb-8c2c-2c384216576f.png)

**Comment by Flightan** [comment]
C'est bon, une config sur netlify qui essayait de rendre le CSS du design system plus compact et cassait en fait le rendu.
<img width="1715" alt="Capture d’écran 2021-04-09 à 11 16 57" src="https://user-images.githubusercontent.com/1475946/114159637-46c42a00-9926-11eb-8cfa-bd800d49a029.png">
