### ISSUE TITLE
Bug moteur de recherche

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#5814]
Quand on fait une recherche dans le moteur de recherche des SE et qu'un résultat tombe sur la vignette d'un produit derrière le pop-up, alors : 
- le clic active la vignette de la SE et non le lien du titre 
![image](https://user-images.githubusercontent.com/43180136/116863891-422e2100-ac07-11eb-80cd-d95555371159.png)

**Comment by astranchet** [comment]
En attendant le composant du DS : 
https://access42.net/concevoir-un-composant-d-auto-completion-accessible

**Comment by astranchet** [comment]
Et c'est déjà en partie corrigé par https://github.com/betagouv/beta.gouv.fr/pull/5756 : on peut merger ?

**Comment by LucasCharrier** [comment]
moi je suis ok pour merge, en attendant d'avoir quelque chose de mieux 👍
