### ISSUE TITLE
Pop-up quand on publie une offre d'emploi sur netlify

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#5852]
Ce pop-up apparaît quand on enregistre l'offre.
![image](https://user-images.githubusercontent.com/43180136/116988546-d6b08600-acd0-11eb-80c5-0b0ba41812ee.png)

**Comment by revolunet** [comment]
toujours d'actu ?

**Comment by revolunet** [comment]
je close ce n'est plus d'actu
