### ISSUE TITLE
Nouveau popup quand on veut modifier une page produit

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#5858]
C'est l'exemple de Mon suivi justice.
J'ai appuyer sur annuler sans trop savoir si c'était la bonne chose à faire

![image](https://user-images.githubusercontent.com/43180136/117107182-79284200-ad81-11eb-913e-6da951719657.png)

**Comment by jdauphant** [comment]
Je pense que c'est quand la page a déjà essayé d'être modifié

**Comment by LeryJ** [comment]
Ca peut se corriger ?
Ou le texte pourrait indiquer ce qu'il faut faire ? 
Le call to action incite à cliquer sur "Ok".

**Comment by revolunet** [comment]
je close ce n'est plus d'actu
