### ISSUE TITLE
Présenter les startups en consolidation avec un screencast

### ISSUE THREAD

**Issue by kemenaran** [betagouv/beta.gouv.fr#615]
_Discuté lors du Grand Séminaire_

Pour renforcer les liens entre les startups, il peut être bon de savoir ce que chaque startup fait.

On a envisagé des sessions de démo de chaque startup – mais l'intérêt de programmer _yet another rendez-vous_ en présentiel est limité.

En revanche un truc utile serait d'avoir un screencast de présentation du produit pour les startups en consolidation. Une vidéo courte de 2-3 minutes pour dérouler le fonctionnement du produit, un peu comme une démo archivable.

Ça serait diffusable à la fois en interne (pour présenter le produit) et en externe (typiquement sur la fiche-produit du site web).

Dans un premier temps on va expérimenter avec deux startups volontaires : @sgmap/tps  et @sgmap/anah , et voir ce que ça donne.

**Comment by Morendil** [comment]
Il y a aussi https://memo.pole-emploi.fr qui en a déjà un (en home!)

**Comment by Morendil** [comment]
En termes d'implémentation on ferait ça comment sur le site ?

**Comment by Morendil** [comment]
Je ferme, on est clairement pas (encore) prêts…
