### ISSUE TITLE
API pour les offres d'emplois

### ISSUE THREAD

**Issue by mquandalle** [betagouv/beta.gouv.fr#6343]
On a une API pour les membres (https://beta.gouv.fr/api/v2/authors.json) et pour les startups (https://beta.gouv.fr/api/v2/startups.json), mais j'ai l'impression qu'on a en pas pour les offres de recrutement `jobs.json`.

On a pas un gros besoin mais l'idée serait juste d'automatiser l'affichage d'un bandeau sur notre site quand on poste une annonce.

![image](https://user-images.githubusercontent.com/1730702/123261100-a1692d00-d4f6-11eb-9a1c-164ad3c5ddc9.png)

**Comment by mquandalle** [comment]
@jdauphant me disait que le plus simple est d'activer le plugin Jekyll pour générer un flux RSS automatiquement, comme ce qui est déjà fait pour le blog.

**Comment by chaibax** [comment]
Un flux RSS des offres me serait super utile. Je pourrais facilement diffuser les nouvelles offres par email ou sur les reseaux sociaux. La cerise sur la gateau, ca serait d'avoir un flux ou un attribut selon le type de métier (DEv, Bizdev etc) cc @LeryJ  #6489

**Comment by mquandalle** [comment]
Ajouté dans #6893 🎉

**Comment by mquandalle** [comment]
Je me permets de ré-ouvrir car le flux RSS ne contient pas le nom de l'équipe / du produit qui a ouvert l'offre de recrutement.
