### ISSUE TITLE
Filtre par type de métier sur la page recrutement

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#6489]
Le problème : 
Je suis dev et je souhaite postuler chez beta.gouv.
Je trouve facilement la page recrutement. 
Néanmoins, j'ai du mal à identifier les offres qui correspondent à mon profil.

La solution : 
Ajouter un filtre permettant de sélectionner le métier qui m'intéresse : développeur, chargé de déploiement, designeuse, cheffe de produit, data scientiste...

Le gain : 
Je vois tout de suite les offres disponibles pour mon profil.
Je gagne du temps.
Je ne passe pas à côté d'une offre.

**Comment by Sw1n** [comment]
Super idée ! Peut-être d'ailleurs par type de fonction recherchée (développement, design, direction artistique, ...)

**Comment by chaibax** [comment]
C'est top comme idée, ca me serait utile poru communiquer sur les offres de recrutement Bizdev par exemple.
