### ISSUE TITLE
Le contact pour "La bonne formation" n'est plus d'actualité

### ISSUE THREAD

**Issue by bzg** [betagouv/beta.gouv.fr#6951]
Bonjour, j'ai tenté d'écrire à `christophe.bonraisin@pole-emploi.fr` de La bonne formation, qui est le contact indiqué sur [cette page](https://beta.gouv.fr/startups/la-bonne-formation.html), mais le mail m'est revenu.

Savez-vous quel serait le bon contact ?

Merci !

**Comment by bzg** [comment]
Gentle ping :)

**Comment by sebpoirotPE** [comment]
Le bon mail est : christ.bonraisin@pole-emploi.fr

**Comment by bzg** [comment]
Merci !

**Comment by bzg** [comment]
Bonjour,

Est-ce que vous pourriez mettre à jour [cette page](https://beta.gouv.fr/startups/la-bonne-formation.html) avec le bon contact ?

**Comment by sebpoirotPE** [comment]
Bonjour, je ne suis pas le référent du produit mais j'ai fait les modifs pour gagner du temps. Sur https://beta.gouv.fr/admin/#/collections/startups le mail est bien christ.bonraisin@pole-emploi.fr.
N'étant pas familier de tout ça, est-ce que ça suffira pour que https://beta.gouv.fr/startups/la-bonne-formation.html se MAJ ? Le lien renvoie toujours vers le mauvais mail (christophe.bonraisin@pole-emploi.fr) actuellement.

**Comment by bzg** [comment]
Je vois que le mail a bien été mis à jour sur https://beta.gouv.fr/startups/la-bonne-formation.html - merci beaucoup d'être intervenu!
