### ISSUE TITLE
Bug liste référent formulaire d'inscription

### ISSUE THREAD

**Issue by LeryJ** [betagouv/beta.gouv.fr#7366]
Quand une personne souhaite se créer un compte beta.gouv, la liste des référents s'arrête à la lettre I
![image](https://user-images.githubusercontent.com/43180136/138426162-61323bcd-e9b5-4fc7-9526-cdef47157347.png)

**Comment by astranchet** [comment]
Mauvais répo (bug de l'espace membre)
