### ISSUE TITLE
Create a link between community and job openings

### ISSUE THREAD

**Issue by maukoquiroga** [betagouv/beta.gouv.fr#743]
# Create a link between community and job openings

Objectif : Augmenter les leads des travailleurs et travailleuses numériques (recrutement)

Histoire :

	Quand je suis en train de chercher une nouvelle mission,
	et que j’en ai marre de travailler tout·e seul·e,
	et que j’en ai marre du « bro » startup bullshit,
	et que je suis un lien qui me mène sur beta.gouv.fr ;

	Je veux savoir qu’est-ce l’incubateur,
	et savoir avec qui pourrais-je être mené·e à travailler, 
	et savoir s’ils ont de postes ouverts ;

	Quand je découvre la communauté de beta.gouv.fr,
	et que je repère Thomas, que je connais dès Devoxx 2015,
	et avec qui j’aimerais bien travailler ;

	Je veux savoir où Thomas intervient-il,
	et savoir si je peux travailler avec lui,
	ou à défaut savoir s’il y a d’autres postes à pourvoir ;
	
	Pour pouvoir travailler avec quelqu’un·e top,
	et/ou entouré·e d’une équipe top,
	et être fière de moi,
	et apprendre beaucoup de choses.

Idée sortie de l'atelier produit :

<img width="1364" alt="landing community" src="https://user-images.githubusercontent.com/329236/26880264-2686ae7c-4b94-11e7-9033-e8a073df6fbc.png">

**Comment by Morendil** [comment]
@maukoquiroga Il reste quoi à faire ?

**Comment by Morendil** [comment]
Le lien est indirect (via la fiche startup) mais il me semble que ça fait le job.

Closed via #980

**Comment by Morendil** [comment]
Je ferme à nouveau cette issue sans avancées constatées sur un trimestre. Plutôt que la réouvrir j'invite à la morceler en tâches réalisables dans un temps relativement court.
