### ISSUE TITLE
bug: date 2029 pour le job SRE ministere sociaux

### ISSUE THREAD

**Issue by adipasquale** [betagouv/beta.gouv.fr#8358]
@revolunet je sais que vous etes en avance mais là vous y allez fort ^^

<img width="552" alt="Screenshot 2022-01-05 at 11 34 15" src="https://user-images.githubusercontent.com/883348/148203622-2c1a87cb-ca00-49e2-8cb1-d5c4b8302f8a.png">

je ne vois pas trop pourquoi ça fait ça, il manque probablement une date dans ton MD

**Comment by revolunet** [comment]
huhu bien vu @adipasquale :) je corrige ca
