### ISSUE TITLE
[Test] Ajouter un test sur le nom des startups

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/beta.gouv.fr#8774]
Pour s assurer que les noms des startups déclarées dans les fiches de membres sont conformes aux noms  (id) de la fiche startup

**Comment by revolunet** [comment]
c'est ajouté dans cette PR : https://github.com/betagouv/beta.gouv.fr/pull/17893

**Comment by revolunet** [comment]
intégré dans https://github.com/betagouv/beta.gouv.fr/pull/18266
