### ISSUE TITLE
Ajouter de nouvelles entrées sur les fiches members pour les transverses et externes

### ISSUE THREAD

**Issue by LucasCharrier** [betagouv/beta.gouv.fr#8882]
# Probleme : 
- les personnes en transverse ne sont rattachés a aucune startup il est donc impossible de les rattacher à une entité.
- certaine personnes externes (membre de benext, octo) ont des fiches mais ne sont pas rattacher non plus à une entité.

# Proposition : 
- ajouter une entrée qui permette des rattacher les transverse à un entité. Un champs incubateur par exemple obligatoire pour toute fiche membre sans startup
- ajouter une entrée boolean externe pour identifier les personnes qui ne sont ni tranverse ni membre d'une startup, ces personnes n'ont en théorie pas d'accès au outils de la communauté, pas d'email, mais éventuellement un compte mattermost

**Comment by Flightan** [comment]
Sans changer le modèle de données je pense qu'il est préférable de creer un nouveau type d'objet qui ressemble fortement à "startups" pour rassembler les équipes transverses (sans les phases probablement).
