### ISSUE TITLE
Mise à jour doc de référence

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/beta.gouv.fr#9855]
Problème : La présentation de référence sur le site beta.gouv.fr n'est pas à jour (exemple : nombre d'incubateur / membre de l'équipe d'animation). 

Où : sur https://beta.gouv.fr/ en bas à gauche
![image](https://user-images.githubusercontent.com/15428433/166236243-51377c20-2244-4c26-a7d5-d9c0a14b3d77.png)

Deux solutions : 
- La rapide et qui fait 99% du taff : Soit mettre à jour avec la présentation la plus à jour que l'on ait [voir ici](https://docs.google.com/presentation/d/19WkJQatZyEHi3mKixjr4dsKMNCJ4Ii7SKyamNDoF2ms/edit?usp=sharing)
- La plus longue et plus complète : Soit lancer un chantier pour créer une nouvelle doc + celle en anglais (en profiter pour mettre des éléments du bilan 2021)

**Comment by revolunet** [comment]
toujours d'actu ?

**Comment by revolunet** [comment]
@margot-sanchez si c'est toujours d'actu tu peux vérifier [cette PR](https://github.com/betagouv/beta.gouv.fr/pull/18314) sinon on ferme cette issue ?

Le fichier actuellement en ligne date de Juin 2021

**Comment by margot-sanchez** [comment]
Oui c'est toujours d'actualités. La présentation montre des membres qui ne sont plus dans l'équipe depuis 2 ans.

**Comment by margot-sanchez** [comment]
Faudrait mettre la présentation faite en webinaire communauté de Ishan. Je n'arrive pas à voir quel pdf tu as mis sur l'autre PR.

**Comment by revolunet** [comment]
il faudrait mettre [celle-ci](https://docs.google.com/presentation/d/1xa7tl-vQGjUfholgxCrea3XP854G9cR9o8gbYrtEmQ0/edit#slide=id.g21344f99820_1_74) ?
