### ISSUE TITLE
📆 Faciliter l'accès à l'agenda public

### ISSUE THREAD

**Issue by chaibax** [betagouv/beta.gouv.fr#9884]
Chez beta, on a pleins d'evenements , chaque semaine . Par exemple : 

- Club Bizdev
- Docteur Design
- Forum beta
- Grand seméinaire
- Cauchemard à beta
- Formations
- Apéros
- Formation Alpha
- Jury Fast 
- Talk avec un invités 

C'est une chance et une vraie plus valus pour nos satartups et partenaires. 

Hélàs, c'est confidentiel. Il faut savoir que notre agenda est disponnible ici : https://calendar.google.com/calendar/embed?src=0ieonqap1r5jeal5ugeuhoovlg%40group.calendar.google.com&ctz=Europe%2FParis 

Avoir un onglet Agenda (ou Evenements) qui pointerait vers notre agenda public serait une bon début.

Avoir une vrai page Evemenent/Agenda sur le site serait encore plus top.

**Comment by Mux199** [comment]
Bonjour,
J'aimerais contribuer à ce projet si cette issue est toujours d'actualité.

**Comment by jdauphant** [comment]
> Chez beta, on a pleins d'evenements , chaque semaine . Par exemple :
> 
> * Club Bizdev
> * Docteur Design
> * Forum beta
> * Grand seméinaire
> * Cauchemard à beta
> * Formations
> * Apéros
> * Formation Alpha
> * Jury Fast
> * Talk avec un invités
> 
> C'est une chance et une vraie plus valus pour nos satartups et partenaires.
> 
> Hélàs, c'est confidentiel. Il faut savoir que notre agenda est disponnible ici : https://calendar.google.com/calendar/embed?src=0ieonqap1r5jeal5ugeuhoovlg%40group.calendar.google.com&ctz=Europe%2FParis
> 
> Avoir un onglet Agenda (ou Evenements) qui pointerait vers notre agenda public serait une bon début.
> 
> Avoir une vrai page Evemenent/Agenda sur le site serait encore plus top.

L'agenda public ne peut pas être publié, il est à destination de la communauté uniquement, il peut être intégrer dans l'espace membre.

Aussi tu peux faire des propositions Chaib mais c'est un peu compliqué que tu mettes "good first issue" si elle n'est pas validé.
